#! /bin/bash

THINGS_TO_COPY="\
*.html \
cgi-bin \
libs \
icons \
*.css \
config/legend_lookup.js
"

rsync --delete --exclude '**/.git*' --delete-excluded -av ${THINGS_TO_COPY} html/

chmod -R a+w html/cgi-bin/print_temp
