var legend_lookup = {
"LANDFIREVegetation": {
    "0": "None",
    "11": "Open Water",
    "12": "Snow-Ice",
    "13": "Developed-Upland Deciduous Forest",
    "14": "Developed-Upland Evergreen Forest",
    "15": "Developed-Upland Mixed Forest",
    "16": "Developed-Upland Herbaceous",
    "17": "Developed-Upland Shrubland",
    "18": "Developed-Herbaceous Wetland Vegetation",
    "19": "Developed-Woody Wetland Vegetation",
    "20": "Developed-General",
    "21": "Developed-Open Space",
    "22": "Developed-Low Intensity",
    "23": "Developed-Medium Intensity",
    "24": "Developed-High Intensity",
    "25": "Developed-Roads",
    "31": "Barren",
    "32": "Quarries-Strip Mines-Gravel Pits",
    "60": "NASS-Orchard",
    "61": "NASS-Vineyard",
    "62": "NASS-Bush fruit and berries",
    "63": "NASS-Row Crop-Close Grown Crop",
    "64": "NASS-Row Crop",
    "65": "NASS-Close Grown Crop",
    "66": "NASS-Fallow/Idle Cropland",
    "67": "NASS-Pasture and Hayland",
    "75": "Herbaceous Semi-dry",
    "76": "Herbaceous Semi-wet",
    "78": "Recently Disturbed Forest",
    "80": "Agriculture-General",
    "81": "Agriculture-Pasture and Hay",
    "82": "Agriculture-Cultivated Crops and Irrigated Agriculture",
    "83": "Agriculture-Small Grains",
    "84": "Agriculture-Fallow",
    "85": "Agriculture-Urban and Recreational Grasses",
    "95": "Herbaceous Wetlands",
    "200": "Unclassified Sparsely Vegetated Systems",
    "201": "Unclassified Forest and Woodland",
    "202": "Unclassified Shrubland",
    "203": "Unclassified Upland Herbaceous",
    "204": "Unclassified Savanna",
    "205": "Unclassified Shrub-Steppe",
    "206": "Unclassified Grassland",
    "207": "Unclassified Wetland-Riparian Herbaceous",
    "2001": "Inter-Mountain Basins Sparsely Vegetated Systems",
    "2002": "Mediterranean California Sparsely Vegetated Systems",
    "2003": "North Pacific Sparsely Vegetated Systems",
    "2004": "North American Warm Desert Sparsely Vegetated Systems",
    "2005": "Pacific Coastal Dunes and Other Sparsely Vegetated Systems",
    "2006": "Rocky Mountain Alpine/Montane Sparsely Vegetated Systems",
    "2007": "Western Great Plains Sparsely Vegetated Systems",
    "2008": "North Pacific Oak Woodland",
    "2009": "Northwestern Great Plains Aspen Forest and Parkland",
    "2010": "Northern Rocky Mountain Western Larch Savanna",
    "2011": "Rocky Mountain Aspen Forest and Woodland",
    "2012": "Rocky Mountain Bigtooth Maple Ravine Woodland",
    "2013": "Western Great Plains Dry Bur Oak Forest and Woodland",
    "2014": "Central and Southern California Mixed Evergreen Woodland",
    "2015": "California Coastal Redwood Forest",
    "2016": "Colorado Plateau Pinyon-Juniper Woodland",
    "2017": "Columbia Plateau Western Juniper Woodland and Savanna",
    "2018": "East Cascades Mesic Montane Mixed-Conifer Forest and Woodland",
    "2019": "Great Basin Pinyon-Juniper Woodland",
    "2020": "Inter-Mountain Basins Subalpine Limber-Bristlecone Pine Woodland",
    "2021": "Klamath-Siskiyou Lower Montane Serpentine Mixed Conifer Woodland",
    "2022": "Klamath-Siskiyou Upper Montane Serpentine Mixed Conifer Woodland",
    "2023": "Madrean Encinal",
    "2024": "Madrean Lower Montane Pine-Oak Forest and Woodland",
    "2025": "Madrean Pinyon-Juniper Woodland",
    "2026": "Madrean Upper Montane Conifer-Oak Forest and Woodland",
    "2027": "Mediterranean California Dry-Mesic Mixed Conifer Forest and Woodland",
    "2028": "Mediterranean California Mesic Mixed Conifer Forest and Woodland",
    "2029": "Mediterranean California Mixed Oak Woodland",
    "2030": "Mediterranean California Lower Montane Black Oak-Conifer Forest and Woodland",
    "2031": "California Montane Jeffrey Pine(-Ponderosa Pine) Woodland",
    "2032": "Mediterranean California Red Fir Forest",
    "2033": "Mediterranean California Subalpine Woodland",
    "2034": "Mediterranean California Mesic Serpentine Woodland and Chaparral",
    "2035": "North Pacific Dry Douglas-fir(-Madrone) Forest and Woodland",
    "2036": "North Pacific Hypermaritime Seasonal Sitka Spruce Forest",
    "2037": "North Pacific Maritime Dry-Mesic Douglas-fir-Western Hemlock Forest",
    "2038": "North Pacific Maritime Mesic Subalpine Parkland",
    "2039": "North Pacific Maritime Mesic-Wet Douglas-fir-Western Hemlock Forest",
    "2040": "North Pacific Mesic Western Hemlock-Yellow-cedar Forest",
    "2041": "North Pacific Mountain Hemlock Forest",
    "2042": "North Pacific Mesic Western Hemlock-Silver Fir Forest",
    "2043": "Mediterranean California Mixed Evergreen Forest",
    "2044": "Northern California Mesic Subalpine Woodland",
    "2045": "Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest",
    "2046": "Northern Rocky Mountain Subalpine Woodland and Parkland",
    "2047": "Northern Rocky Mountain Mesic Montane Mixed Conifer Forest",
    "2048": "Northwestern Great Plains Highland White Spruce Woodland",
    "2049": "Rocky Mountain Foothill Limber Pine-Juniper Woodland",
    "2050": "Rocky Mountain Lodgepole Pine Forest",
    "2051": "Southern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest and Woodland",
    "2052": "Southern Rocky Mountain Mesic Montane Mixed Conifer Forest and Woodland",
    "2053": "Northern Rocky Mountain Ponderosa Pine Woodland and Savanna",
    "2054": "Southern Rocky Mountain Ponderosa Pine Woodland",
    "2055": "Rocky Mountain Subalpine Dry-Mesic Spruce-Fir Forest and Woodland",
    "2056": "Rocky Mountain Subalpine Mesic-Wet Spruce-Fir Forest and Woodland",
    "2057": "Rocky Mountain Subalpine-Montane Limber-Bristlecone Pine Woodland",
    "2058": "Sierra Nevada Subalpine Lodgepole Pine Forest and Woodland",
    "2059": "Southern Rocky Mountain Pinyon-Juniper Woodland",
    "2060": "East Cascades Oak-Ponderosa Pine Forest and Woodland",
    "2061": "Inter-Mountain Basins Aspen-Mixed Conifer Forest and Woodland",
    "2062": "Inter-Mountain Basins Curl-leaf Mountain Mahogany Woodland and Shrubland",
    "2063": "North Pacific Broadleaf Landslide Forest and Shrubland",
    "2064": "Colorado Plateau Mixed Low Sagebrush Shrubland",
    "2065": "Columbia Plateau Scabland Shrubland",
    "2066": "Inter-Mountain Basins Mat Saltbush Shrubland",
    "2067": "Mediterranean California Alpine Fell-Field",
    "2068": "North Pacific Dry and Mesic Alpine Dwarf-Shrubland or Fell-field or Meadow",
    "2069": "North Pacific Mesic Low Shrubland",
    "2070": "Rocky Mountain Alpine Dwarf-Shrubland",
    "2071": "Sierra Nevada Alpine Dwarf-Shrubland",
    "2072": "Wyoming Basins Dwarf Sagebrush Shrubland and Steppe",
    "2073": "Baja Semi-Desert Coastal Succulent Scrub",
    "2074": "Chihuahuan Creosotebush Desert Scrub",
    "2075": "Chihuahuan Mixed Salt Desert Scrub",
    "2076": "Chihuahuan Stabilized Coppice Dune and Sand Flat Scrub",
    "2077": "Chihuahuan Succulent Desert Scrub",
    "2078": "Colorado Plateau Blackbrush-Mormon-tea Shrubland",
    "2079": "Great Basin Xeric Mixed Sagebrush Shrubland",
    "2080": "Inter-Mountain Basins Big Sagebrush Shrubland",
    "2081": "Inter-Mountain Basins Mixed Salt Desert Scrub",
    "2082": "Mojave Mid-Elevation Mixed Desert Scrub",
    "2083": "North Pacific Avalanche Chute Shrubland",
    "2084": "North Pacific Montane Shrubland",
    "2085": "Northwestern Great Plains Shrubland",
    "2086": "Rocky Mountain Lower Montane-Foothill Shrubland",
    "2087": "Sonora-Mojave Creosotebush-White Bursage Desert Scrub",
    "2088": "Sonora-Mojave Mixed Salt Desert Scrub",
    "2089": "Sonoran Brittlebush-Ironwood Desert Scrub",
    "2090": "Sonoran Granite Outcrop Desert Scrub",
    "2091": "Sonoran Mid-Elevation Desert Scrub",
    "2092": "Southern California Coastal Scrub",
    "2093": "Southern Colorado Plateau Sand Shrubland",
    "2094": "Western Great Plains Sandhill Steppe",
    "2095": "Apacherian-Chihuahuan Mesquite Upland Scrub",
    "2096": "California Maritime Chaparral",
    "2097": "California Mesic Chaparral",
    "2098": "California Montane Woodland and Chaparral",
    "2099": "California Xeric Serpentine Chaparral",
    "2100": "Chihuahuan Mixed Desert and Thornscrub",
    "2101": "Madrean Oriental Chaparral",
    "2102": "Colorado Plateau Pinyon-Juniper Shrubland",
    "2103": "Great Basin Semi-Desert Chaparral",
    "2104": "Mogollon Chaparral",
    "2105": "Northern and Central California Dry-Mesic Chaparral",
    "2106": "Northern Rocky Mountain Montane-Foothill Deciduous Shrubland",
    "2107": "Rocky Mountain Gambel Oak-Mixed Montane Shrubland",
    "2108": "Sonora-Mojave Semi-Desert Chaparral",
    "2109": "Sonoran Paloverde-Mixed Cacti Desert Scrub",
    "2110": "Southern California Dry-Mesic Chaparral",
    "2111": "Western Great Plains Mesquite Woodland and Shrubland",
    "2112": "California Central Valley Mixed Oak Savanna",
    "2113": "California Coastal Live Oak Woodland and Savanna",
    "2114": "California Lower Montane Blue Oak-Foothill Pine Woodland and Savanna",
    "2115": "Inter-Mountain Basins Juniper Savanna",
    "2116": "Madrean Juniper Savanna",
    "2117": "Southern Rocky Mountain Ponderosa Pine Savanna",
    "2118": "Southern California Oak Woodland and Savanna",
    "2119": "Southern Rocky Mountain Juniper Woodland and Savanna",
    "2120": "Willamette Valley Upland Prairie and Savanna",
    "2121": "Apacherian-Chihuahuan Semi-Desert Grassland and Steppe",
    "2122": "Chihuahuan Gypsophilous Grassland and Steppe",
    "2123": "Columbia Plateau Steppe and Grassland",
    "2124": "Columbia Plateau Low Sagebrush Steppe",
    "2125": "Inter-Mountain Basins Big Sagebrush Steppe",
    "2126": "Inter-Mountain Basins Montane Sagebrush Steppe",
    "2127": "Inter-Mountain Basins Semi-Desert Shrub-Steppe",
    "2128": "Northern California Coastal Scrub",
    "2129": "California Central Valley and Southern Coastal Grassland",
    "2130": "California Mesic Serpentine Grassland",
    "2131": "California Northern Coastal Grassland",
    "2132": "Central Mixedgrass Prairie",
    "2133": "Chihuahuan Sandy Plains Semi-Desert Grassland",
    "2134": "Columbia Basin Foothill and Canyon Dry Grassland",
    "2135": "Inter-Mountain Basins Semi-Desert Grassland",
    "2136": "Mediterranean California Alpine Dry Tundra",
    "2137": "Mediterranean California Subalpine Meadow",
    "2138": "North Pacific Montane Grassland",
    "2139": "Northern Rocky Mountain Lower Montane-Foothill-Valley Grassland",
    "2140": "Northern Rocky Mountain Subalpine-Upper Montane Grassland",
    "2141": "Northwestern Great Plains Mixedgrass Prairie",
    "2142": "Columbia Basin Palouse Prairie",
    "2143": "Rocky Mountain Alpine Fell-Field",
    "2144": "Rocky Mountain Alpine Turf",
    "2145": "Rocky Mountain Subalpine-Montane Mesic Meadow",
    "2146": "Southern Rocky Mountain Montane-Subalpine Grassland",
    "2147": "Western Great Plains Foothill and Piedmont Grassland",
    "2148": "Western Great Plains Sand Prairie",
    "2149": "Western Great Plains Shortgrass Prairie",
    "2150": "Western Great Plains Tallgrass Prairie",
    "2151": "California Central Valley Riparian Woodland and Shrubland",
    "2152": "California Montane Riparian Systems",
    "2153": "Inter-Mountain Basins Greasewood Flat",
    "2154": "Inter-Mountain Basins Montane Riparian Systems",
    "2155": "North American Warm Desert Riparian Systems",
    "2156": "North Pacific Lowland Riparian Forest and Shrubland",
    "2157": "North Pacific Swamp Systems",
    "2158": "North Pacific Montane Riparian Woodland and Shrubland",
    "2159": "Rocky Mountain Montane Riparian Systems",
    "2160": "Rocky Mountain Subalpine/Upper Montane Riparian Systems",
    "2161": "Northern Rocky Mountain Conifer Swamp",
    "2162": "Western Great Plains Floodplain Systems",
    "2163": "Pacific Coastal Marsh Systems",
    "2164": "Rocky Mountain Wetland-Herbaceous",
    "2165": "Northern Rocky Mountain Foothill Conifer Wooded Steppe",
    "2166": "Middle Rocky Mountain Montane Douglas-fir Forest and Woodland",
    "2167": "Rocky Mountain Poor-Site Lodgepole Pine Forest",
    "2168": "Northern Rocky Mountain Avalanche Chute Shrubland",
    "2169": "Northern Rocky Mountain Subalpine Deciduous Shrubland",
    "2170": "Klamath-Siskiyou Xeromorphic Serpentine Savanna and Chaparral",
    "2171": "North Pacific Alpine and Subalpine Dry Grassland",
    "2172": "Sierran-Intermontane Desert Western White Pine-White Fir Woodland",
    "2173": "North Pacific Wooded Volcanic Flowage",
    "2174": "North Pacific Dry-Mesic Silver Fir-Western Hemlock-Douglas-fir Forest",
    "2175": "North Pacific Interior Spruce-Fir Forest and Woodland",
    "2177": "California Coastal Closed-Cone Conifer Forest and Woodland",
    "2178": "North Pacific Hypermaritime Western Red-cedar-Western Hemlock Forest",
    "2179": "Northwestern Great Plains-Black Hills Ponderosa Pine Woodland and Savanna",
    "2180": "Introduced Riparian Vegetation",
    "2181": "Introduced Upland Vegetation-Annual Grassland",
    "2182": "Introduced Upland Vegetation-Perennial Grassland and Forbland",
    "2183": "Introduced Upland Vegetation-Annual and Biennial Forbland",
    "2184": "California Annual Grassland",
    "2185": "Introduced Wetland Vegetation-Mixed",
    "2186": "Introduced Upland Vegetation-Shrub",
    "2187": "Introduced Upland Vegetation-Treed",
    "2188": "Transitional Herbacous Vegetation",
    "2189": "Transitional Shrub Vegetation",
    "2190": "Cultivated Crops and Irrigated Agriculture",
    "2191": "Recently Logged-Herb and Grass Cover",
    "2192": "Recently Logged-Shrub Cover",
    "2193": "Recently Logged-Tree Cover",
    "2194": "Ruderal Upland-Treed",
    "2195": "Recently Burned-Herb and Grass Cover",
    "2196": "Recently Burned-Shrub Cover",
    "2197": "Recently Burned-Tree Cover",
    "2198": "Recently Burned Herbaceous Wetlands",
    "2200": "Pseudotsuga menziesii-Quercus garryana Woodland Alliance",
    "2201": "Quercus garryana Woodland Alliance",
    "2202": "Juniperus occidentalis Wooded Herbaceous Alliance",
    "2203": "Juniperus occidentalis Woodland Alliance",
    "2204": "Tsuga heterophylla Giant Forest Alliance",
    "2205": "Tsuga mertensiana-Abies amabilis Woodland Alliance",
    "2206": "Pseudotsuga menziesii Giant Forest Alliance",
    "2207": "Chamaecyparis nootkatensis Forest Alliance",
    "2208": "Abies concolor Forest Alliance",
    "2210": "Coleogyne ramosissima Shrubland Alliance",
    "2211": "Grayia spinosa Shrubland Alliance",
    "2212": "Artemisia filifolia Shrubland Alliance",
    "2213": "Quercus havardii Shrubland Alliance",
    "2214": "Arctostaphylos patula Shrubland Alliance",
    "2215": "Quercus turbinella Shrubland Alliance",
    "2216": "Cercocarpus montanus Shrubland Alliance",
    "2217": "Quercus gambelii Shrubland Alliance",
    "2218": "Purshia tridentata Shrubland Alliance",
    "2219": "Artemisia arbuscula ssp. arbuscula Shrubland Alliance",
    "2220": "Artemisia tridentata ssp. vaseyana Shrubland Alliance",
    "2221": "Yucca glauca Shrub Herbaceous Alliance",
    "2222": "Artemisia tridentata ssp. wyomingensis Shrub Herbaceous Alliance",
    "2223": "Gutierrezia sarothrae Dwarf-Shrubland Alliance",
    "2224": "Elaeagnus angustifolia Semi-Natural Woodland Alliance",
    "2225": "Tamarisk spp. Semi-Natural Temporarily Flooded Shrubland Alliance",
    "2226": "Bromus spp. Semi-Natural Herbaceous Alliance",
    "2227": "Pseudotsuga menziesii Forest Alliance",
    "2228": "Larix occidentalis Forest Alliance",
    "2229": "Pinus albicaulis Woodland Alliance",
    "2230": "Pinus sabiniana Woodland Alliance",
    "2231": "Sequoiadendron giganteum Forest Alliance",
    "2232": "Abies grandis Forest Alliance",
    "2301": "Boreal Aspen-Birch Forest",
    "2302": "Laurentian-Acadian Northern Hardwoods Forest",
    "2303": "Northeastern Interior Dry-Mesic Oak Forest",
    "2304": "Ozark-Ouachita Dry-Mesic Oak Forest",
    "2305": "Southern Interior Low Plateau Dry-Mesic Oak Forest",
    "2306": "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland",
    "2307": "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest",
    "2308": "Crosstimbers Oak Forest and Woodland",
    "2309": "Southern Appalachian Northern Hardwood Forest",
    "2310": "North-Central Interior Dry-Mesic Oak Forest and Woodland",
    "2311": "North-Central Interior Dry Oak Forest and Woodland",
    "2312": "Ouachita Montane Oak Forest",
    "2313": "North-Central Interior Beech-Maple Forest",
    "2314": "North-Central Interior Maple-Basswood Forest",
    "2315": "Southern Appalachian Oak Forest",
    "2316": "Southern Piedmont Mesic Forest",
    "2317": "Allegheny-Cumberland Dry Oak Forest and Woodland",
    "2318": "Southern and Central Appalachian Cove Forest",
    "2320": "Central and Southern Appalachian Montane Oak Forest",
    "2321": "South-Central Interior Mesophytic Forest",
    "2322": "Crowley's Ridge Mesic Loess Slope Forest",
    "2323": "West Gulf Coastal Plain Mesic Hardwood Forest",
    "2324": "Northern Atlantic Coastal Plain Hardwood Forest",
    "2325": "East Gulf Coastal Plain Northern Mesic Hardwood Slope Forest",
    "2326": "South-Central Interior/Upper Coastal Plain Flatwoods",
    "2327": "East Gulf Coastal Plain Northern Loess Bluff Forest",
    "2328": "Southern Coastal Plain Limestone Forest",
    "2329": "East Gulf Coastal Plain Southern Loess Bluff Forest",
    "2330": "Southern Coastal Plain Dry Upland Hardwood Forest",
    "2331": "Eastern Great Plains Tallgrass Aspen Parkland",
    "2333": "South Florida Hardwood Hammock",
    "2334": "Ozark-Ouachita Mesic Hardwood Forest",
    "2335": "Southern Atlantic Coastal Plain Dry and Dry-Mesic Oak Forest",
    "2336": "Southwest Florida Coastal Strand and Maritime Hammock",
    "2337": "Southeast Florida Coastal Strand and Maritime Hammock",
    "2338": "Central and South Texas Coastal Fringe Forest and Woodland",
    "2339": "West Gulf Coastal Plain Chenier and Upper Texas Coastal Fringe Forest and Woodland",
    "2340": "Appalachian Shale Barrens",
    "2341": "Northwestern Great Plains Canyon",
    "2342": "Piedmont Hardpan Woodland and Forest",
    "2343": "Southern Atlantic Coastal Plain Mesic Hardwood Forest",
    "2344": "Boreal Jack Pine-Black Spruce Forest",
    "2346": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland",
    "2347": "Atlantic Coastal Plain Upland Longleaf Pine Woodland",
    "2348": "West Gulf Coastal Plain Upland Longleaf Pine Forest and Woodland",
    "2349": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland",
    "2350": "Central and Southern Appalachian Spruce-Fir Forest",
    "2351": "Southeastern Interior Longleaf Pine Woodland",
    "2352": "Southern Appalachian Montane Pine Forest and Woodland",
    "2353": "Southern Appalachian Low-Elevation Pine Forest",
    "2354": "Northeastern Interior Pine Barrens",
    "2355": "Northern Atlantic Coastal Plain Pitch Pine Barrens",
    "2356": "Florida Longleaf Pine Sandhill",
    "2357": "Southern Coastal Plain Mesic Slope Forest",
    "2358": "East-Central Texas Plains Pine Forest and Woodland",
    "2360": "South Florida Pine Rockland",
    "2361": "Central Atlantic Coastal Plain Maritime Forest",
    "2362": "Laurentian-Acadian Northern Pine(-Oak) Forest",
    "2363": "Central Interior Highlands Dry Acidic Glade and Barrens",
    "2364": "Ozark-Ouachita Dry Oak Woodland",
    "2365": "Boreal White Spruce-Fir-Hardwood Forest",
    "2366": "Laurentian-Acadian Pine-Hemlock-Hardwood Forest",
    "2367": "Ozark-Ouachita Shortleaf Pine-Oak Forest and Woodland",
    "2368": "Southern Piedmont Dry Oak(-Pine) Forest",
    "2369": "Central Appalachian Dry Oak-Pine Forest",
    "2370": "Appalachian (Hemlock-)Northern Hardwood Forest",
    "2371": "West Gulf Coastal Plain Pine-Hardwood Forest",
    "2372": "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest",
    "2373": "Acadian Low-Elevation Spruce-Fir-Hardwood Forest",
    "2374": "Acadian-Appalachian Montane Spruce-Fir Forest",
    "2375": "Eastern Serpentine Woodland",
    "2376": "Southern Ridge and Valley/Cumberland Dry Calcareous Forest",
    "2377": "Central Appalachian Pine-Oak Rocky Woodland",
    "2378": "West Gulf Coastal Plain Sandhill Oak and Shortleaf Pine Forest and Woodland",
    "2379": "Northern Atlantic Coastal Plain Maritime Forest",
    "2380": "East Gulf Coastal Plain Maritime Forest",
    "2381": "Lower Mississippi River Dune Woodland and Forest",
    "2382": "Southern Atlantic Coastal Plain Maritime Forest",
    "2383": "Edwards Plateau Limestone Savanna and Woodland",
    "2384": "Mississippi Delta Maritime Forest",
    "2385": "Western Great Plains Wooded Draw and Ravine",
    "2386": "Acadian-Appalachian Alpine Tundra",
    "2387": "Florida Peninsula Inland Scrub",
    "2389": "Acadian-Appalachian Subalpine Woodland and Heath-Krummholz",
    "2390": "Tamaulipan Mixed Deciduous Thornscrub",
    "2391": "Tamaulipan Mesquite Upland Scrub",
    "2392": "Tamaulipan Calcareous Thornscrub",
    "2393": "Edwards Plateau Limestone Shrubland",
    "2394": "North-Central Interior Oak Savanna",
    "2395": "North-Central Oak Barrens",
    "2397": "Nashville Basin Limestone Glade and Woodland",
    "2398": "Cumberland Sandstone Glade and Barrens",
    "2400": "Central Appalachian Alkaline Glade and Woodland",
    "2401": "Central Interior Highlands Calcareous Glade and Barrens",
    "2403": "West Gulf Coastal Plain Catahoula Barrens",
    "2405": "West Gulf Coastal Plain Nepheline Syenite Glade",
    "2407": "Laurentian Pine-Oak Barrens",
    "2408": "Alabama Ketona Glade and Woodland",
    "2409": "Great Lakes Alvar",
    "2410": "Llano Uplift Acidic Forest-Woodland-Glade",
    "2411": "Great Lakes Wet-Mesic Lakeplain Prairie",
    "2412": "North-Central Interior Sand and Gravel Tallgrass Prairie",
    "2413": "Bluegrass Savanna and Woodland",
    "2414": "Southern Appalachian Grass and Shrub Bald",
    "2415": "Arkansas Valley Prairie and Woodland",
    "2416": "Western Highland Rim Prairie and Barrens",
    "2417": "Eastern Highland Rim Prairie and Barrens",
    "2418": "Pennyroyal Karst Plain Prairie and Barrens",
    "2419": "Southern Ridge and Valley Patch Prairie",
    "2420": "Northern Tallgrass Prairie",
    "2421": "Central Tallgrass Prairie",
    "2422": "Texas Blackland Tallgrass Prairie",
    "2423": "Southeastern Great Plains Tallgrass Prairie",
    "2425": "Florida Dry Prairie",
    "2426": "Southern Atlantic Coastal Plain Dune and Maritime Grassland",
    "2428": "West Gulf Coastal Plain Northern Calcareous Prairie",
    "2429": "West Gulf Coastal Plain Southern Calcareous Prairie",
    "2430": "Southern Coastal Plain Blackland Prairie and Woodland",
    "2433": "East Gulf Coastal Plain Jackson Prairie and Woodland",
    "2434": "Texas-Louisiana Coastal Prairie",
    "2435": "East Gulf Coastal Plain Dune and Coastal Grassland",
    "2436": "Northern Atlantic Coastal Plain Dune and Swale",
    "2437": "Central and Upper Texas Coast Dune and Coastal Grassland",
    "2438": "Tamaulipan Savanna Grassland",
    "2439": "South Texas Lomas",
    "2440": "Tamaulipan Clay Grassland",
    "2441": "Tamaulipan Tallgrass Grassland",
    "2442": "South Texas Sand Sheet Grassland",
    "2443": "South Texas Dune and Coastal Grassland",
    "2444": "Eastern Boreal Floodplain",
    "2445": "South Florida Dwarf Cypress Savanna",
    "2446": "South Florida Pine Flatwoods",
    "2447": "South Florida Cypress Dome",
    "2449": "Central Atlantic Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "2450": "Southern Atlantic Coastal Plain Wet Pine Savanna and Flatwoods",
    "2451": "West Gulf Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "2452": "Atlantic Coastal Plain Peatland Pocosin and Canebrake",
    "2453": "Central Florida Pine Flatwoods",
    "2454": "East Gulf Coastal Plain Near-Coast Pine Flatwoods",
    "2455": "East Gulf Coastal Plain Southern Loblolly-Hardwood Flatwoods",
    "2456": "Northern Atlantic Coastal Plain Pitch Pine Lowland",
    "2457": "South-Central Interior/Upper Coastal Plain Wet Flatwoods",
    "2458": "West Gulf Coastal Plain Pine-Hardwood Flatwoods",
    "2459": "Atlantic Coastal Plain Clay-Based Carolina Bay Wetland",
    "2460": "Southern Coastal Plain Nonriverine Cypress Dome",
    "2461": "Southern Coastal Plain Seepage Swamp and Baygall",
    "2462": "West Gulf Coastal Plain Seepage Swamp and Baygall",
    "2466": "Great Lakes Wooded Dune and Swale",
    "2467": "Tamaulipan Floodplain",
    "2468": "Atlantic Coastal Plain Streamhead Seepage Swamp-Pocosin-Baygall",
    "2469": "Eastern Great Plains Floodplain Systems",
    "2470": "Caribbean Coastal Wetland Systems",
    "2471": "Central Interior and Appalachian Floodplain Systems",
    "2472": "Central Interior and Appalachian Riparian Systems",
    "2473": "Gulf and Atlantic Coastal Plain Floodplain Systems",
    "2474": "Gulf and Atlantic Coastal Plain Small Stream Riparian Systems",
    "2475": "Laurentian-Acadian Floodplain Systems",
    "2476": "Tamaulipan Riparian Systems",
    "2477": "Boreal Acidic Peatland Systems",
    "2478": "Caribbean Swamp Systems",
    "2479": "Central Interior and Appalachian Swamp Systems",
    "2480": "Gulf and Atlantic Coastal Plain Swamp Systems",
    "2481": "Laurentian-Acadian Alkaline Conifer-Hardwood Swamp",
    "2482": "Great Plains Prairie Pothole",
    "2483": "South Florida Everglades Sawgrass Marsh",
    "2484": "South Florida Wet Marl Prairie",
    "2485": "East Gulf Coastal Plain Savanna and Wet Prairie",
    "2486": "Texas Saline Coastal Prairie",
    "2488": "Eastern Great Plains Wet Meadow-Prairie-Marsh",
    "2489": "Floridian Highlands Freshwater Marsh",
    "2490": "Gulf and Atlantic Coastal Plain Tidal Marsh Systems",
    "2491": "Acadian Salt Marsh and Estuary Systems",
    "2492": "Great Lakes Coastal Marsh Systems",
    "2493": "Central Interior and Appalachian Shrub-Herbaceous Wetland Systems",
    "2494": "Laurentian-Acadian Shrub-Herbaceous Wetland Systems",
    "2495": "Western Great Plains Depressional Wetland Systems",
    "2497": "Central Interior and Appalachian Sparsely Vegetated Systems",
    "2498": "Gulf and Atlantic Coastal Plain Sparsely Vegetated Systems",
    "2499": "Laurentian-Acadian Sparsely Vegetated Systems",
    "2501": "Southern Atlantic Coastal Plain Nonriverine Swamp and Wet Hardwood Forest",
    "2503": "Chihuahuan Loamy Plains Desert Grassland",
    "2504": "Chihuahuan-Sonoran Desert Bottomland and Swale Grassland",
    "2506": "West Gulf Coastal Plain Nonriverine Wet Hardwood Flatwoods",
    "2507": "Ozark-Ouachita Shortleaf Pine-Bluestem Woodland",
    "2509": "Mississippi River Alluvial Plain Dry-Mesic Loess Slope Forest",
    "2510": "Crowley's Ridge Sand Forest",
    "2513": "Lower Mississippi River Flatwoods",
    "2516": "Atlantic Coastal Plain Sandhill Seep",
    "2517": "Paleozoic Plateau Bluff and Talus",
    "2518": "North-Central Interior Wet Flatwoods",
    "2519": "East-Central Texas Plains Post Oak Savanna and Woodland",
    "2521": "West Gulf Coastal Plain Stream Terrace Sandyland Longleaf Pine Woodland",
    "2522": "Northern Atlantic Coastal Plain Heathland and Grassland",
    "2523": "Edwards Plateau Dry-Mesic Slope Forest and Woodland",
    "2524": "Edwards Plateau Mesic Canyon",
    "2525": "Edwards Plateau Riparian",
    "2526": "Laurentian-Acadian Swamp Systems",
    "2530": "Ruderal Wetland",
    "2531": "Ruderal Upland-Old Field",
    "2532": "Ruderal Forest-Northern and Central Hardwood and Conifer",
    "2533": "Ruderal Forest-Southeast Hardwood and Conifer",
    "2534": "Managed Tree Plantation-Northern and Central Hardwood and Conifer Plantation Group",
    "2535": "Managed Tree Plantation-Southeast Conifer and Hardwood Plantation Group",
    "2536": "Introduced Wetland Vegetation-Tree",
    "2537": "Introduced Wetland Vegetation-Shrub",
    "2538": "Introduced Wetland Vegetation-Herbaceous",
    "2539": "Modified-Managed Northern Tall Grassland",
    "2540": "Modified-Managed Southern Tall Grassland",
    "2541": "Recently Disturbed Developed Upland Deciduous Forest",
    "2542": "Recently Disturbed Developed Upland Evergreen Forest",
    "2543": "Recently Disturbed Developed Upland Mixed Forest",
    "2544": "Recently Disturbed Developed Upland Herbaceous",
    "2545": "Recently Disturbed Developed Upland Shrubland",
    "2546": "Recently Disturbed Developed Herbaceous Wetland Vegetation",
    "2547": "Recently Disturbed Developed Woody Wetland Vegetation",
    "2548": "Recently Disturbed Orchard Vegetation",
    "2549": "Recently Disturbed Pasture and Hayland",
    "2550": "Pinus taeda Forest Alliance",
    "2551": "Pinus elliottii Saturated Temperate Woodland Alliance",
    "2552": "Pinus palustris-Pinus elliottii Forest Alliance",
    "2553": "Mixed Loblolly-Slash Pine",
    "2554": "Norway Spruce Forest",
    "2555": "Scotch Pine Forest",
    "2557": "Pinus strobus Forest Alliance",
    "2558": "Pinus resinosa Forest Alliance",
    "2559": "Pinus virginiana Forest Alliance",
    "2560": "Pinus banksiana Forest Alliance",
    "2600": "Western North American Boreal White Spruce Forest",
    "2601": "Western North American Boreal Treeline White Spruce Woodland",
    "2602": "Western North American Boreal Spruce-Lichen Woodland",
    "2603": "Western North American Boreal White Spruce-Hardwood Forest",
    "2604": "Western North American Boreal Mesic Black Spruce Forest",
    "2605": "Western North American Boreal Mesic Birch-Aspen Forest",
    "2606": "Western North American Boreal Dry Aspen-Steppe Bluff",
    "2607": "Western North American Boreal Subalpine Balsam Poplar-Aspen Woodland",
    "2608": "Alaska Sub-boreal Avalanche Slope Shrubland",
    "2609": "Alaska Sub-boreal Mesic Subalpine Alder Shrubland",
    "2610": "Western North American Boreal Mesic Scrub Birch-Willow Shrubland",
    "2611": "Western North American Sub-boreal Mesic Bluejoint Meadow",
    "2612": "Western North American Boreal Dry Grassland",
    "2613": "Western North American Boreal Active Inland Dune",
    "2614": "Western North American Boreal Montane Floodplain Forest and Shrubland",
    "2615": "Western North American Boreal Lowland Large River Floodplain Forest and Shrubland",
    "2616": "Western North American Boreal Riparian Stringer Forest and Shrubland",
    "2617": "Western North American Boreal Shrub and Herbaceous Floodplain Wetland",
    "2618": "Western North American Boreal Herbaceous Fen",
    "2619": "Western North American Boreal Sedge-Dwarf-Shrub Bog",
    "2620": "Western North American Boreal Low Shrub Peatland",
    "2621": "Western North American Boreal Black Spruce Dwarf-Tree Peatland",
    "2622": "Western North American Boreal Black Spruce Wet-Mesic Slope Woodland",
    "2623": "Western North American Boreal Black Spruce-Tamarack Fen",
    "2624": "Western North American Boreal Deciduous Shrub Swamp",
    "2625": "Western North American Boreal Freshwater Emergent Marsh",
    "2626": "Western North American Boreal Wet Meadow",
    "2627": "Western North American Boreal Freshwater Aquatic Bed",
    "2628": "Western North American Boreal Low Shrub-Tussock Tundra",
    "2629": "Western North American Boreal Tussock Tundra",
    "2630": "Western North American Boreal Wet Black Spruce-Tussock Woodland",
    "2631": "Western North American Boreal Alpine Dwarf-Shrub Summit",
    "2632": "Western North American Boreal Alpine Talus and Bedrock",
    "2633": "Western North American Boreal Alpine Mesic Herbaceous Meadow",
    "2634": "Western North American Boreal Alpine Dryas Dwarf-Shrubland",
    "2635": "Western North American Boreal Alpine Ericaceous Dwarf-Shrubland",
    "2636": "Western North American Boreal Alpine Dwarf-Shrub-Lichen Shrubland",
    "2637": "Western North American Boreal Alpine Floodplain",
    "2638": "Alaska Arctic Mesic Alder Shrubland",
    "2639": "Alaska Arctic Mesic-Wet Willow Shrubland",
    "2640": "Aleutian Mesic-Wet Willow Shrubland",
    "2642": "Aleutian Kenai Birch-Cottonwood-Poplar Forest",
    "2643": "Alaskan Pacific Maritime Alpine Dwarf-Shrubland",
    "2644": "Alaskan Pacific Maritime Sitka Spruce Forest",
    "2645": "Alaska Sub-boreal and Maritime Alpine Mesic Herbaceous Meadow",
    "2646": "Alaskan Pacific Maritime Western Hemlock Forest",
    "2647": "Aleutian Shrub-Sedge Peatland",
    "2648": "Alaskan Pacific Maritime Mountain Hemlock Forest",
    "2649": "Alaskan Pacific Maritime Subalpine Mountain Hemlock Woodland",
    "2650": "Alaskan Pacific Maritime Periglacial Woodland and Shrubland",
    "2651": "Aleutian Mesic Herbaceous Meadow",
    "2652": "Alaskan Pacific Maritime Subalpine Alder-Salmonberry Shrubland",
    "2653": "Alaskan Pacific Maritime Mesic Herbaceous Meadow",
    "2654": "Alaskan Pacific Maritime Sitka Spruce Beach Ridge",
    "2655": "Alaskan Pacific Maritime Floodplain Forest and Shrubland",
    "2656": "Alaskan Pacific Maritime Shrub and Herbaceous Floodplain Wetland",
    "2657": "Alaskan Pacific Maritime Shore Pine Peatland",
    "2658": "Alaskan Pacific Maritime Dwarf-shrub-Sphagnum Peatland",
    "2659": "Alaskan Pacific Maritime Mountain Hemlock Peatland",
    "2660": "Alaskan Pacific Maritime Wet Low Shrubland",
    "2661": "Alaskan Pacific Maritime Fen and Wet Meadow",
    "2662": "Temperate Pacific Freshwater Emergent Marsh",
    "2663": "North Pacific Shrub Swamp",
    "2664": "Temperate Pacific Freshwater Aquatic Bed",
    "2665": "Alaskan Pacific Maritime Coastal Meadow and Slough-Levee",
    "2666": "Alaskan Pacific Maritime Coastal Dune-Beach and Beach Meadow",
    "2667": "Alaskan Pacific Maritime Rocky Coastline",
    "2668": "Temperate Pacific Tidal Salt and Brackish Marsh",
    "2669": "Temperate Pacific Intertidal Flat",
    "2670": "North Pacific Maritime Eelgrass Bed",
    "2671": "Aleutian American Dunegrass Grassland",
    "2672": "Alaskan Pacific Maritime Subalpine Copperbush Shrubland",
    "2673": "Alaskan Pacific Maritime Alpine Wet Meadow",
    "2674": "Alaskan Pacific Maritime Alpine Sparse Shrub and Fell-field",
    "2676": "Alaskan Pacific Maritime Alpine Floodplain",
    "2677": "Alaska Sub-boreal White-Lutz Spruce Forest and Woodland",
    "2678": "Alaska Sub-boreal Mountain Hemlock-White Spruce Forest",
    "2679": "Alaska Sub-boreal White Spruce-Hardwood Forest",
    "2680": "Alaskan Pacific Maritime Avalanche Slope Shrubland",
    "2681": "Alaskan Pacific Maritime Poorly Drained Conifer Woodland",
    "2682": "Alaska Arctic Scrub Birch-Ericaceous Shrubland",
    "2683": "Alaska Arctic Mesic Sedge-Willow Tundra",
    "2684": "Alaska Arctic Mesic Sedge-Dryas Tundra",
    "2685": "Alaska Arctic Acidic Sparse Tundra",
    "2686": "Alaska Arctic Non-Acidic Sparse Tundra",
    "2687": "Alaska Arctic Lichen Tundra",
    "2688": "Alaska Arctic Acidic Dryas Dwarf-Shrubland",
    "2689": "Alaska Arctic Non-Acidic Dryas Dwarf-Shrubland",
    "2690": "Alaska Arctic Dwarf-Shrubland",
    "2691": "Alaska Arctic Acidic Dwarf-Shrub Lichen Tundra",
    "2692": "Alaska Arctic Non-Acidic Dwarf-Shrub Lichen Tundra",
    "2693": "Alaska Arctic Shrub-Tussock Tundra",
    "2694": "Alaska Arctic Tussock Tundra",
    "2695": "Alaska Arctic Tussock-Lichen Tundra",
    "2696": "Alaska Arctic Freshwater Aquatic Bed",
    "2697": "Alaska Arctic Pendantgrass Freshwater Marsh",
    "2698": "Alaska Arctic Wet Sedge Meadow",
    "2699": "Alaska Arctic Mesic Herbaceous Meadow",
    "2700": "Alaska Arctic Polygonal Ground Mesic Shrub Tundra",
    "2701": "Alaska Arctic Coastal Sedge-Dwarf-Shrubland",
    "2702": "Alaska Arctic Wet Sedge-Sphagnum Peatland",
    "2703": "Alaska Arctic Dwarf-Shrub-Sphagnum Peatland",
    "2704": "Alaska Arctic Permafrost Plateau Dwarf-Shrub Lichen Tundra",
    "2705": "Alaska Arctic Sedge Freshwater Marsh",
    "2706": "Alaska Arctic Polygonal Ground Wet Sedge Tundra",
    "2707": "Alaska Arctic Polygonal Ground Tussock Tundra",
    "2708": "Alaska Arctic Polygonal Ground Shrub-Tussock Tundra",
    "2709": "Alaska Arctic Marine Beach and Beach Meadow",
    "2710": "Alaska Arctic Tidal Flat",
    "2711": "Alaska Arctic Tidal Marsh",
    "2712": "Alaska Arctic Coastal Brackish Meadow",
    "2713": "Alaska Arctic Active Inland Dune",
    "2714": "Alaska Arctic Large River Floodplain",
    "2715": "Alaska Arctic Floodplain",
    "2716": "Aleutian Rocky Headland and Sea Cliff",
    "2717": "Alaska Arctic Bedrock and Talus",
    "2718": "Aleutian Mesic Alder-Salmonberry Shrubland",
    "2719": "Aleutian Crowberry-Herbaceous Heath",
    "2720": "Aleutian Mixed Dwarf-Shrub-Herbaceous Shrubland",
    "2721": "Aleutian Freshwater Aquatic Bed",
    "2722": "Aleutian Freshwater Marsh",
    "2723": "Aleutian Wet Meadow and Herbaceous Peatland",
    "2724": "Aleutian Nonvascular Peatland",
    "2725": "Aleutian Marine Beach and Beach Meadow",
    "2726": "Aleutian Tidal Marsh",
    "2727": "Aleutian Shrub and Herbaceous Meadow Floodplain",
    "2728": "Aleutian Floodplain Forest and Shrubland",
    "2729": "Aleutian Floodplain Wetland",
    "2730": "Aleutian Sparse Heath and Fell-Field",
    "2731": "Aleutian Oval-leaf Blueberry Shrubland",
    "2732": "Aleutian Volcanic Rock and Talus",
    "2733": "North Pacific Montane Massive Bedrock-Cliff and Talus",
    "2734": "North Pacific Alpine and Subalpine Bedrock and Scree",
    "2735": "North American Glacier and Ice Field",
    "2740": "Boreal Aquatic Beds",
    "2741": "Polar Tidal Marshes and Aquatic Beds",
    "2742": "Temperate Pacific Tidal Marshes, Aquatic Beds, and Intertidal Flats",
    "2743": "Aleutian Herbaceous Wetlands",
    "2744": "Arctic Herbaceous Wetlands",
    "2745": "Boreal Herbaceous Wetlands",
    "2746": "Pacific Maritime Herbaceous Wetlands",
    "2747": "Arctic Sedge Meadows",
    "2749": "Pacific Maritime Coastal Meadows and Slough-Levee",
    "2751": "Boreal Coniferous Woody Wetland",
    "2752": "Pacific Maritime Coniferous Woody Wetland",
    "2753": "Boreal Coniferous-Deciduous Woody Wetland",
    "2756": "Arctic Dwarf Shrub Wetland",
    "2757": "Boreal Dwarf Shrub Wetland",
    "2758": "Pacific Maritime Dwarf Shrub Wetland",
    "2761": "Aleutian Floodplains",
    "2762": "Arctic Floodplains",
    "2763": "Boreal Floodplains",
    "2764": "Pacific Maritime Floodplains",
    "2771": "Aleutian Peatlands",
    "2772": "Arctic Peatlands",
    "2773": "Boreal Peatlands",
    "2774": "Pacific Maritime Peatlands",
    "2776": "Boreal Riparian Stringer Forest and Shrubland",
    "2777": "Boreal Shrub Swamp",
    "2778": "Pacific Maritime Shrub Swamp",
    "2781": "Arctic Sedge-Tussock-Lichen Tundra",
    "2782": "Boreal Tussock Tundra",
    "2783": "Arctic Tussock Tundra",
    "2784": "Arctic Shrub-Tussock Tundra",
    "2785": "Arctic Shrub Tundra",
    "2786": "Boreal Shrub-Tussock Tundra",
    "2791": "Aleutian Sparsely Vegetated",
    "2792": "Arctic Sparsely Vegetated",
    "2793": "Boreal Sparsely Vegetated",
    "2794": "Pacific Maritime Sparsely Vegetated",
    "2806": "Hawai'i Bog",
    "2808": "Hawai'i Lowland Rainforest",
    "2809": "Hawai'i Montane Cloud Forest",
    "2810": "Hawai'i Montane Rainforest",
    "2811": "Hawai'i Wet Cliff and Ridge Crest Shrubland",
    "2813": "Hawai'i Lowland Dry Forest",
    "2814": "Hawai'i Lowland Mesic Forest",
    "2815": "Hawai'i Montane-Subalpine Dry Forest and Woodland",
    "2816": "Hawai'i Montane-Subalpine Mesic Forest",
    "2817": "Hawai'i Lowland Dry Shrubland",
    "2818": "Hawai'i Lowland Mesic Shrubland",
    "2819": "Hawai'i Lowland Dry Grassland",
    "2820": "Hawai'i Lowland Mesic Grassland",
    "2821": "Hawai'i Montane-Subalpine Dry Shrubland",
    "2822": "Hawai'i Montane-Subalpine Dry Grassland",
    "2823": "Hawai'i Montane-Subalpine Mesic Grassland",
    "2824": "Hawai'i Alpine Dwarf-Shrubland",
    "2825": "Hawai'i Dry Cliff",
    "2826": "Hawai'i Dry Coastal Strand",
    "2827": "Hawai'i Wet-Mesic Coastal Strand",
    "2828": "Hawai'i Subalpine Mesic Shrubland",
    "2829": "Hawai'i Alpine Bedrock and Scree",
    "2831": "Hawai'i Dry-Site Lava Flow",
    "2836": "Hawaiian Introduced Wetland Vegetation-Tree",
    "2837": "Hawaiian Introduced Wetland Vegetation-Shrub",
    "2838": "Hawaiian Introduced Wetland Vegetation-Herbaceous",
    "2845": "Hawaiian Introduced Dry Forest",
    "2846": "Hawaiian Introduced Wet-Mesic Forest",
    "2847": "Hawaiian Introduced Deciduous Shrubland",
    "2848": "Hawaiian Introduced Perennial Grassland",
    "2849": "Hawaiian Introduced Evergreen Shrubland",
    "2852": "Introduced Coastal Wetland Vegetation - Tree",
    "2853": "Introduced Coastal Wetland Vegetation - Shrub",
    "2854": "Introduced Coastal Wetland Vegetation - Herbaceous",
    "2855": "Hawaiian Managed Tree Plantation"
  },
  "forest-type": {
    "1": "Jack Pine",
    "2": "Red Pine",
    "3": "Eastern White Pine",
    "4": "Eastern White Pine/Eastern Hemlock",
    "5": "Eastern Hemlock",
    "6": "Balsam Fir",
    "7": "White Spruce",
    "8": "Red Spruce",
    "9": "Red Spruce/Balsam Fir",
    "10": "Black Spruce",
    "11": "Tamarack",
    "12": "Northern White-cedar",
    "13": "Longleaf Pine",
    "14": "Slash Pine",
    "15": "Loblolly Pine",
    "16": "Shortleaf Pine",
    "17": "Virginia Pine",
    "18": "Sand Pine",
    "19": "Table-mountain Pine",
    "20": "Pond Pine",
    "21": "Pitch Pine",
    "22": "Spruce Pine",
    "23": "Eastern Redcedar",
    "24": "Rocky Mountain Juniper",
    "25": "Western Juniper",
    "26": "Juniper Woodland",
    "27": "Pinyon Juniper Woodland",
    "28": "Douglas-fir",
    "29": "Port-orford-cedar",
    "30": "Ponderosa Pine",
    "31": "Jeffrey Pine/Coulter Pine/Bigcon",
    "32": "Sugar Pine",
    "33": "Western White Pine",
    "34": "White Fir",
    "35": "Red Fir",
    "36": "Noble Fir",
    "37": "Pacific Silver Fir",
    "38": "Engelmann Spruce",
    "39": "Engelmann Spruce/Subalpine Fir",
    "40": "Grand Fir",
    "41": "Subalpine Fir",
    "42": "Blue Spruce",
    "43": "Mountain Hemlock",
    "44": "Alaska-yellow-cedar",
    "45": "Lodgepole Pine",
    "46": "Western Hemlock",
    "47": "Western Redcedar",
    "48": "Sitka Spruce",
    "49": "Western Larch",
    "50": "Redwood",
    "51": "Giant Sequoia",
    "52": "Knobcone Pine",
    "53": "Foxtail Pine/Bristlecone Pine",
    "54": "Limber Pine",
    "55": "Whitebark Pine",
    "56": "Misc. Western Softwoods",
    "57": "California Mixed Conifer",
    "58": "Scotch Pine",
    "59": "Other Exotic Softwoods",
    "60": "Norway Spruce",
    "61": "Eastern White Pine/Northern Red",
    "62": "Eastern Redcedar/Hardwood",
    "63": "Longleaf Pine/Oak",
    "64": "Shortleaf Pine/Oak",
    "65": "Virginia Pine/Southern Red Oak",
    "66": "Loblolly Pine/Hardwood",
    "67": "Slash Pine/Hardwood",
    "68": "Other Pine/Hardwood",
    "69": "Post Oak/Blackjack Oak",
    "70": "Chestnut Oak",
    "71": "White Oak/Red Oak/Hickory",
    "72": "White Oak",
    "73": "Northern Red Oak",
    "74": "Yellow-poplar/White Oak/Northern",
    "75": "Sassafras/Persimmon",
    "76": "Sweetgum/Yellow-poplar",
    "77": "Bur Oak",
    "78": "Scarlet Oak",
    "79": "Yellow-poplar",
    "80": "Black Walnut",
    "81": "Black Locust",
    "82": "Southern Scrub Oak",
    "83": "Chestnut Oak/Black Oak/Scarlet O",
    "84": "Red Maple/Oak",
    "85": "Mixed Upland Hardwoods",
    "86": "Swamp Chestnut Oak/Cherrybark Oa",
    "87": "Sweetgum/Nuttall Oak/Willow Oak",
    "88": "Overcup Oak/Water Hickory",
    "89": "Atlantic White-cedar",
    "90": "Baldcypress/Water Tupelo",
    "91": "Sweetbay/Swamp Tupelo/Red Maple",
    "92": "Black Ash/American Elm/Red Maple",
    "93": "River Birch/Sycamore",
    "94": "Cottonwood",
    "95": "Willow",
    "96": "Sycamore/Pecan/American Elm",
    "97": "Sugarberry/Hackberry/Elm/Green A",
    "98": "Silver Maple/American Elm",
    "99": "Red Maple/Lowland",
    "100": "Cottonwood/Willow",
    "101": "Oregon Ash",
    "102": "Sugar Maple/Beech/Yellow Birch",
    "103": "Black Cherry",
    "104": "Cherry/Ash/Yellow-poplar",
    "105": "Hard Maple/Basswood",
    "106": "Elm/Ash/Locust",
    "107": "Red Maple/Upland",
    "108": "Aspen",
    "109": "Paper Birch",
    "110": "Gray Birch",
    "111": "Balsam Poplar",
    "112": "Red Alder",
    "113": "Bigleaf Maple",
    "114": "Gray Pine",
    "115": "California Black Oak",
    "116": "Oregon White Oak",
    "117": "Blue Oak",
    "118": "Deciduous Oak Woodland",
    "119": "Evergreen Oak",
    "120": "Coast Live Oak",
    "121": "Canyon Live Oak/Interior Live Oa",
    "122": "Tanoak",
    "123": "California Laurel",
    "124": "Giant Chinkapin",
    "125": "Pacific Madrone",
    "126": "Mesquite Woodland",
    "127": "Cerocarpus Woodland",
    "128": "Intermountain Maple Woodland",
    "129": "Misc. Western Hardwood Woodlands",
    "130": "Sable Palm",
    "131": "Mangrove",
    "132": "Eucalyptus"
  },
  "forest-group": {
    "28": "White/Red/Jack Pine Group",
    "22": "Spruce/Fir Group",
    "12": "Longleaf/Slash Pine Group",
    "10": "Loblolly/Shortleaf Pine Group",
    "19": "Pinyon/Juniper Group",
    "4": "Douglas-fir Group",
    "20": "Ponderosa Pine Group",
    "27": "Western White Pine Group",
    "8": "Fir/Spruce/Mountain Hemlock Grou",
    "11": "Lodgepole Pine Group",
    "9": "Hemlock/Sitka Spruce Group",
    "25": "Western Larch Group",
    "21": "Redwood Group",
    "18": "Other Western Softwoods Group",
    "3" : "California Mixed Conifer Group",
    "7" : "Exotic Softwoods Group",
    "16": "Oak/Pine Group",
    "15": "Oak/Hickory Group",
    "14": "Oak/Gum/Cypress Group",
    "5": "Elm/Ash/Cottonwood Group",
    "13": "Maple/Beech/Birch Group",
    "2": "Aspen/Birch Group",
    "1": "Alder/Maple Group",
    "26": "Western Oak Group",
    "23": "Tanoak/Laurel Group",
    "17": "Other Western Hardwoods Group",
    "24": "Tropical Hardwoods Group",
    "6": "Exotic Hardwoods Group"
  },
  "nlcd-2006": {
    "11": "Open Water",
    "12": "Perennial Snow/Ice",
    "21": "Developed, Open Space",
    "22": "Developed, Low Intensity",
    "23": "Developed, Medium Intensity",
    "24": "Developed, High Intensity",
    "31": "Barren Land",
    "41": "Deciduous Forest",
    "42": "Evergreen Forest",
    "43": "Mixed Forest",
    "52": "Shrub/Scrub",
    "71": "Herbaceuous",
    "81": "Hay/Pasture",
    "82": "Cultivated Crops",
    "90": "Woody Wetlands",
    "95": "Emergent Herbaceuous Wetlands"
  },
  "gapnat-2001": {
    "1201": "Developed, Open Space",
    "1202": "Developed, Low Intensity",
    "1203": "Developed, Medium Intensity",
    "1204": "Developed, High Intensity",
    "1301": "Quarries, Mines, Gravel Pits and Oil Wells",
    "1401": "Orchards Vineyards and Other High Structure Agriculture",
    "1402": "Cultivated Cropland",
    "1403": "Pasture/Hay",
    "2102": "Open Water (Fresh)",
    "2103": "Open Water (Brackish/Salt)",
    "2104": "Open Water (Aquaculture)",
    "3105": "Undifferentiated Barren Land",
    "3106": "Atlantic Coastal Plain Northern Sandy Beach",
    "3107": "Atlantic Coastal Plain Southern Beach",
    "3110": "Unconsolidated Shore",
    "3111": "North American Warm Desert Active and Stabilized Dune",
    "3112": "Northern Atlantic Coastal Plain Sandy Beach",
    "3113": "Upper Texas Coast Beach",
    "3114": "Louisiana Beach",
    "3115": "Southeast Florida Beach",
    "3116": "Great Lakes Dune",
    "3117": "South Florida Shell Hash Beach",
    "3118": "Florida Panhandle Beach Vegetation",
    "3119": "Atlantic Coastal Plain Sea Island Beach",
    "3120": "Southwest Florida Beach",
    "3121": "Inter-Mountain Basins Active and Stabilized Dune",
    "3122": "Mediterranean California Southern Coastal Dune",
    "3123": "Mediterranean California Northern Coastal Dune",
    "3124": "North Pacific Maritime Coastal Sand Dune and Strand",
    "3125": "Texas Coastal Bend Beach",
    "3201": "North American Warm Desert Bedrock Cliff and Outcrop",
    "3202": "Rocky Mountain Cliff, Canyon and Massive Bedrock",
    "3203": "Western Great Plains Cliff and Outcrop",
    "3204": "Great Lakes Acidic Rocky Shore and Cliff",
    "3205": "Central Interior Calcareous Cliff and Talus",
    "3206": "Central Interior Acidic Cliff and Talus",
    "3207": "North-Central Appalachian Circumneutral Cliff and Talus",
    "3208": "North-Central Appalachian Acidic Cliff and Talus",
    "3209": "North Pacific Montane Massive Bedrock, Cliff and Talus",
    "3210": "Southern Piedmont Cliff",
    "3211": "North Pacific Coastal Cliff and Bluff",
    "3212": "Southern California Coast Ranges Cliff and Canyon",
    "3213": "Central California Coast Ranges Cliff and Canyon",
    "3214": "Klamath-Siskiyou Cliff and Outcrop",
    "3215": "Sierra Nevada Cliff and Canyon",
    "3216": "Inter-Mountain Basins Cliff and Canyon",
    "3217": "Southwestern Great Plains Canyon",
    "3218": "Colorado Plateau Mixed Bedrock Canyon and Tableland",
    "3219": "Southern Interior Acid Cliff",
    "3220": "Southern Appalachian Montane Cliff",
    "3221": "Southern Interior Calcareous Cliff",
    "3301": "Western Great Plains Badland",
    "3302": "East Gulf Coastal Plain Dry Chalk Bluff",
    "3303": "North American Warm Desert Badland",
    "3304": "Inter-Mountain Basins Shale Badland",
    "3305": "Mediterranean California Coastal Bluff",
    "3306": "Columbia Plateau Ash and Tuff Badland",
    "3401": "Temperate Pacific Intertidal Mudflat",
    "3402": "Temperate Pacific Freshwater Mudflat",
    "3403": "Inter-Mountain Basins Wash",
    "3404": "North Pacific Serpentine Barren",
    "3405": "North American Warm Desert Playa",
    "3406": "Mediterranean California Serpentine Barrens",
    "3407": "Inter-Mountain Basins Playa",
    "3501": "North Pacific Alpine and Subalpine Bedrock and Scree",
    "3502": "North American Alpine Ice Field",
    "3503": "Rocky Mountain Alpine Bedrock and Scree",
    "3504": "Mediterranean California Alpine Bedrock and Scree",
    "3506": "Southern Appalachian Rocky Summit",
    "3601": "Geysers and Hot Springs",
    "3602": "Southern Appalachian Granitic Dome",
    "3603": "Inter-Mountain Basins Volcanic Rock and Cinder Land",
    "3604": "North Pacific Volcanic Rock and Cinder Land",
    "3605": "North American Warm Desert Pavement",
    "3606": "Southern Piedmont Granite Flatrock",
    "3607": "North American Warm Desert Volcanic Rockland",
    "4101": "Central and Southern Appalachian Northern Hardwood Forest",
    "4102": "East Gulf Coastal Plain Limestone Forest",
    "4103": "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland - Hardwood Modifier",
    "4104": "Northeastern Interior Dry Oak Forest-Hardwood Modifier",
    "4105": "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland - Juniper Modifier",
    "4106": "Northeastern Interior Dry Oak Forest - Mixed Modifier",
    "4107": "Ridge and Valley Calcareous Valley Bottom Glade and Woodland",
    "4108": "East Gulf Coastal Plain Black Belt Calcareous Prairie and Woodland - Herbaceous Modifier",
    "4109": "Southern and Central Appalachian Oak Forest - Xeric",
    "4110": "North Pacific Oak Woodland",
    "4111": "Rocky Mountain Aspen Forest and Woodland",
    "4112": "Rocky Mountain Bigtooth Maple Ravine Woodland",
    "4113": "Laurentian-Acadian Northern Hardwoods Forest",
    "4114": "Northeastern Interior Dry-Mesic Oak Forest",
    "4115": "Ozark-Ouachita Dry-Mesic Oak Forest",
    "4116": "Southern Interior Low Plateau Dry-Mesic Oak Forest",
    "4117": "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest",
    "4118": "Crosstimbers Oak Forest and Woodland",
    "4119": "Southern Appalachian Northern Hardwood Forest",
    "4120": "North-Central Interior Dry-Mesic Oak Forest and Woodland",
    "4121": "North-Central Interior Dry Oak Forest and Woodland",
    "4122": "Ouachita Montane Oak Forest",
    "4123": "North-Central Interior Beech-Maple Forest",
    "4124": "North-Central Interior Maple-Basswood Forest",
    "4125": "Southern and Central Appalachian Oak Forest",
    "4126": "Allegheny-Cumberland Dry Oak Forest and Woodland - Hardwood",
    "4127": "Central and Southern Appalachian Montane Oak Forest",
    "4128": "East Gulf Coastal Plain Northern Loess Bluff Forest",
    "4129": "East Gulf Coastal Plain Southern Loess Bluff Forest",
    "4130": "Southern Coastal Plain Dry Upland Hardwood Forest",
    "4131": "Eastern Great Plains Tallgrass Aspen Parkland",
    "4132": "South Florida Hardwood Hammock",
    "4133": "Atlantic Coastal Plain Dry and Dry-Mesic Oak Forest",
    "4134": "Southwest Florida Coastal Strand and Maritime Hammock",
    "4135": "Southeast Florida Coastal Strand and Maritime Hammock",
    "4136": "Central and South Texas Coastal Fringe Forest and Woodland",
    "4137": "West Gulf Coastal Plain Chenier and Upper Texas Coastal Fringe Forest and Woodland",
    "4138": "Northwestern Great Plains Aspen Forest and Parkland",
    "4139": "Mississippi River Alluvial Plain Dry-Mesic Loess Slope Forest",
    "4140": "East-Central Texas Plains Post Oak Savanna and Woodland",
    "4141": "East-Central Texas Plains Riparian Forest",
    "4142": "East-Central Texas Plains Floodplain Forest",
    "4143": "Madrean Encinal",
    "4144": "Mediterranean California Mixed Oak Woodland",
    "4145": "South Florida Pine Rockland",
    "4146": "Southern Coastal Plain Oak Dome and Hammock",
    "4147": "Inter-Mountain Basins Curl-leaf Mountain Mahogany Woodland and Shrubland",
    "4148": "North Pacific Broadleaf Landslide Forest and Shrubland",
    "4149": "Ozark-Ouachita Dry Oak Woodland",
    "4150": "East Gulf Coastal Plain Maritime Forest",
    "4151": "Lower Mississippi River Dune Woodland and Forest",
    "4152": "Edwards Plateau Limestone Savanna and Woodland",
    "4153": "Mississippi Delta Maritime Forest",
    "4154": "Western Great Plains Wooded Draw and Ravine",
    "4155": "Edwards Plateau Dry-Mesic Slope Forest and Woodland",
    "4201": "Boreal Aspen-Birch Forest",
    "4202": "Southern Piedmont Mesic Forest",
    "4203": "Southern Crowley's Ridge Mesic Loess Slope Forest",
    "4204": "West Gulf Coastal Plain Mesic Hardwood Forest",
    "4205": "East Gulf Coastal Plain Northern Mesic Hardwood Forest",
    "4206": "South-Central Interior/Upper Coastal Plain Wet Flatwoods",
    "4207": "Ozark-Ouachita Mesic Hardwood Forest",
    "4208": "Edwards Plateau Mesic Canyon",
    "4209": "East Gulf Coastal Plain Southern Mesic Slope Forest",
    "4210": "Atlantic Coastal Plain Central Maritime Forest",
    "4211": "Atlantic Coastal Plain Northern Maritime Forest",
    "4212": "Atlantic Coastal Plain Southern Maritime Forest",
    "4301": "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest - Hardwood Modifier",
    "4302": "Southern Piedmont Dry Oak-(Pine) Forest - Hardwood Modifier",
    "4303": "East Gulf Coastal Plain Black Belt Calcareous Prairie and Woodland - Woodland Modifier",
    "4304": "Northeastern Interior Dry Oak Forest - Virginia/Pitch Pine Modifier",
    "4305": "Southern Piedmont Dry Oak-(Pine) Forest - Loblolly Pine Modifier",
    "4306": "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest - Offsite Pine Modifier",
    "4307": "Allegheny-Cumberland Dry Oak Forest and Woodland - Pine Modifier",
    "4308": "Southern Ridge and Valley Dry Calcareous Forest - Pine modifier",
    "4309": "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest - Mixed Modifier",
    "4310": "Southern Piedmont Dry Oak-(Pine) Forest - Mixed Modifier",
    "4312": "Western Great Plains Dry Bur Oak Forest and Woodland",
    "4313": "Northern Atlantic Coastal Plain Dry Hardwood Forest",
    "4314": "Appalachian Shale Barrens",
    "4315": "Madrean Pine-Oak Forest and Woodland",
    "4316": "Madrean Upper Montane Conifer-Oak Forest and Woodland",
    "4317": "Mediterranean California Lower Montane Black Oak-Conifer Forest and Woodland",
    "4318": "Mediterranean California Red Fir Forest",
    "4319": "North Pacific Dry Douglas-fir-(Madrone) Forest and Woodland",
    "4320": "Mediterranean California Mixed Evergreen Forest",
    "4321": "West Gulf Coastal Plain Upland Longleaf Pine Forest and Woodland",
    "4322": "Southeastern Interior Longleaf Pine Woodland",
    "4323": "Laurentian-Acadian Northern Pine-(Oak) Forest",
    "4324": "Inter-Mountain Basins Aspen-Mixed Conifer Forest and Woodland",
    "4325": "Central Interior Highlands Dry Acidic Glade and Barrens",
    "4326": "Boreal White Spruce-Fir-Hardwood Forest",
    "4327": "Laurentian-Acadian Pine-Hemlock-Hardwood Forest",
    "4328": "Ozark-Ouachita Shortleaf Pine-Oak Forest and Woodland",
    "4329": "Southern Piedmont Dry Oak-(Pine) Forest",
    "4330": "Central Appalachian Oak and Pine Forest",
    "4331": "Appalachian Hemlock-Hardwood Forest",
    "4332": "West Gulf Coastal Plain Pine-Hardwood Forest",
    "4333": "Acadian Low-Elevation Spruce-Fir-Hardwood Forest",
    "4334": "Southern Ridge and Valley Dry Calcareous Forest",
    "4335": "Central Appalachian Pine-Oak Rocky Woodland",
    "4336": "West Gulf Coastal Plain Sandhill Oak and Shortleaf Pine Forest and Woodland",
    "4337": "Northern Crowley's Ridge Sand Forest",
    "4338": "North Pacific Lowland Mixed Hardwood-Conifer Forest and Woodland",
    "4401": "Southern and Central Appalachian Cove Forest",
    "4402": "South-Central Interior Mesophytic Forest",
    "4403": "Atlantic Coastal Plain Mesic Hardwood and Mixed Forest",
    "4404": "Mediterranean California Mesic Serpentine Woodland and Chaparral",
    "4501": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Offsite Hardwood Modifier",
    "4502": "Florida Longleaf Pine Sandhill- Open Understory Modifier",
    "4503": "Florida Longleaf Pine Sandhill - Scrub/Shrub Understory Modifier",
    "4504": "Atlantic Coastal Plain Fall-Line Sandhills Longleaf Pine Woodland - Loblolly Modifier",
    "4505": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Open Understory",
    "4506": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Scrub/Shrub Understory",
    "4507": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Loblolly Modifier",
    "4508": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Open Understory Modifier",
    "4509": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Scrub/Shrub Modifier",
    "4510": "Northern Rocky Mountain Western Larch Savanna",
    "4511": "Central and Southern California Mixed Evergreen Woodland",
    "4512": "Colorado Plateau Pinyon-Juniper Woodland",
    "4513": "Columbia Plateau Western Juniper Woodland and Savanna",
    "4514": "Great Basin Pinyon-Juniper Woodland",
    "4515": "Inter-Mountain Basins Subalpine Limber-Bristlecone Pine Woodland",
    "4516": "Klamath-Siskiyou Lower Montane Serpentine Mixed Conifer Woodland",
    "4517": "Klamath-Siskiyou Upper Montane Serpentine Mixed Conifer Woodland",
    "4518": "Madrean Pinyon-Juniper Woodland",
    "4519": "Mediterranean California Dry-Mesic Mixed Conifer Forest and Woodland",
    "4520": "California Montane Jeffrey Pine-(Ponderosa Pine) Woodland",
    "4521": "Mediterranean California Subalpine Woodland",
    "4522": "North Pacific Maritime Dry-Mesic Douglas-fir-Western Hemlock Forest",
    "4523": "North Pacific Mountain Hemlock Forest",
    "4524": "Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest",
    "4525": "Northern Rocky Mountain Subalpine Woodland and Parkland",
    "4526": "Rocky Mountain Foothill Limber Pine-Juniper Woodland",
    "4527": "Rocky Mountain Lodgepole Pine Forest",
    "4528": "Southern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest and Woodland",
    "4529": "Northern Rocky Mountain Ponderosa Pine Woodland and Savanna",
    "4530": "Southern Rocky Mountain Ponderosa Pine Woodland",
    "4531": "Rocky Mountain Subalpine Dry-Mesic Spruce-Fir Forest and Woodland",
    "4532": "Rocky Mountain Subalpine-Montane Limber-Bristlecone Pine Woodland",
    "4533": "Sierra Nevada Subalpine Lodgepole Pine Forest and Woodland",
    "4534": "Southern Rocky Mountain Pinyon-Juniper Woodland",
    "4535": "Boreal Jack Pine-Black Spruce Forest",
    "4536": "Atlantic Coastal Plain Upland Longleaf Pine Woodland",
    "4537": "Southern Appalachian Montane Pine Forest and Woodland",
    "4538": "Southern Appalachian Low Mountain Pine Forest",
    "4539": "Northeastern Interior Pine Barrens",
    "4540": "Northern Atlantic Coastal Plain Pitch Pine Barrens",
    "4541": "East-Central Texas Plains Pine Forest and Woodland",
    "4542": "Laurentian Jack Pine-Red Pine Forest",
    "4543": "Middle Rocky Mountain Montane Douglas-fir Forest and Woodland",
    "4544": "Rocky Mountain Poor-Site Lodgepole Pine Forest",
    "4545": "California Coastal Closed-Cone Conifer Forest and Woodland",
    "4546": "Sierran-Intermontane Desert Western White Pine-White Fir Woodland",
    "4547": "North Pacific Dry-Mesic Silver Fir-Western Hemlock-Douglas-fir Forest",
    "4548": "Northwestern Great Plains - Black Hills Ponderosa Pine Woodland and Savanna",
    "4549": "Ozark-Ouachita Shortleaf Pine-Bluestem Woodland",
    "4550": "East Cascades Oak-Ponderosa Pine Forest and Woodland",
    "4551": "Acadian-Appalachian Montane Spruce-Fir Forest",
    "4552": "North Pacific Wooded Volcanic Flowage",
    "4553": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Offsite Hardwood",
    "4601": "California Coastal Redwood Forest",
    "4602": "East Cascades Mesic Montane Mixed-Conifer Forest and Woodland",
    "4603": "Mediterranean California Mesic Mixed Conifer Forest and Woodland",
    "4604": "North Pacific Hypermaritime Sitka Spruce Forest",
    "4605": "North Pacific Maritime Mesic Subalpine Parkland",
    "4606": "North Pacific Maritime Mesic-Wet Douglas-fir-Western Hemlock Forest",
    "4607": "North Pacific Mesic Western Hemlock-Silver Fir Forest",
    "4608": "Northern California Mesic Subalpine Woodland",
    "4609": "Northern Rocky Mountain Mesic Montane Mixed Conifer Forest",
    "4610": "Southern Rocky Mountain Mesic Montane Mixed Conifer Forest and Woodland",
    "4611": "Rocky Mountain Subalpine Mesic Spruce-Fir Forest and Woodland",
    "4612": "Central and Southern Appalachian Spruce-Fir Forest",
    "4613": "North Pacific Hypermaritime Western Red-cedar-Western Hemlock Forest",
    "5101": "Mediterranean California Alpine Fell-Field",
    "5102": "North Pacific Dry and Mesic Alpine Dwarf-Shrubland, Fell-field and Meadow",
    "5103": "Rocky Mountain Alpine Dwarf-Shrubland",
    "5104": "Rocky Mountain Alpine Tundra/Fell-field/Dwarf-shrub Map Unit",
    "5105": "Acadian-Appalachian Alpine Tundra",
    "5106": "North Pacific Avalanche Chute Shrubland",
    "5107": "Acadian-Appalachian Subalpine Woodland and Heath-Krummholz",
    "5201": "Chihuahuan Creosotebush, Mixed Desert and Thorn Scrub",
    "5202": "Chihuahuan Mixed Salt Desert Scrub",
    "5203": "Chihuahuan Stabilized Coppice Dune and Sand Flat Scrub",
    "5204": "Chihuahuan Succulent Desert Scrub",
    "5205": "Inter-Mountain Basins Mixed Salt Desert Scrub",
    "5206": "Mojave Mid-Elevation Mixed Desert Scrub",
    "5207": "Sonora-Mojave Creosotebush-White Bursage Desert Scrub",
    "5208": "Sonora-Mojave Mixed Salt Desert Scrub",
    "5209": "Sonoran Mid-Elevation Desert Scrub",
    "5210": "Southern California Coastal Scrub",
    "5211": "Apacherian-Chihuahuan Mesquite Upland Scrub",
    "5212": "Chihuahuan Mixed Desert and Thorn Scrub",
    "5213": "Sonoran Paloverde-Mixed Cacti Desert Scrub",
    "5214": "Florida Peninsula Inland Scrub",
    "5215": "Tamaulipan Mixed Deciduous Thornscrub",
    "5216": "Tamaulipan Mesquite Upland Scrub",
    "5217": "Tamaulipan Calcareous Thornscrub",
    "5218": "Northern California Coastal Scrub",
    "5301": "Western Great Plains Sandhill Steppe",
    "5302": "Northern Rocky Mountain Foothill Conifer Wooded Steppe",
    "5303": "Apacherian-Chihuahuan Semi-Desert Grassland and Steppe",
    "5304": "Chihuahuan Gypsophilous Grassland and Steppe",
    "5305": "Columbia Plateau Steppe and Grassland",
    "5306": "Columbia Plateau Low Sagebrush Steppe",
    "5307": "Inter-Mountain Basins Big Sagebrush Steppe",
    "5308": "Inter-Mountain Basins Montane Sagebrush Steppe",
    "5309": "Inter-Mountain Basins Semi-Desert Shrub Steppe",
    "5401": "California Maritime Chaparral",
    "5402": "California Mesic Chaparral",
    "5403": "California Montane Woodland and Chaparral",
    "5404": "California Xeric Serpentine Chaparral",
    "5405": "Madrean Oriental Chaparral",
    "5406": "Great Basin Semi-Desert Chaparral",
    "5407": "Mogollon Chaparral",
    "5408": "Northern and Central California Dry-Mesic Chaparral",
    "5409": "Sonora-Mojave Semi-Desert Chaparral",
    "5410": "Southern California Dry-Mesic Chaparral",
    "5411": "Coahuilan Chaparral",
    "5501": "California Central Valley Mixed Oak Savanna",
    "5502": "California Coastal Live Oak Woodland and Savanna",
    "5503": "California Lower Montane Blue Oak-Foothill Pine Woodland and Savanna",
    "5504": "Southern California Oak Woodland and Savanna",
    "5505": "Willamette Valley Upland Prairie and Savanna",
    "5506": "North-Central Interior Oak Savanna",
    "5507": "North-Central Oak Barrens",
    "5508": "Southern Piedmont Glade and Barrens",
    "5509": "Nashville Basin Limestone Glade",
    "5511": "Central Appalachian Alkaline Glade and Woodland",
    "5512": "Central Interior Highlands Calcareous Glade and Barrens",
    "5513": "West Gulf Coastal Plain Catahoula Barrens",
    "5514": "West Gulf Coastal Plain Nepheline Syenite Glade",
    "5515": "Laurentian Pine-Oak Barrens",
    "5516": "Klamath-Siskiyou Xeromorphic Serpentine Savanna and Chaparral",
    "5517": "Paleozoic Plateau Bluff and Talus",
    "5601": "Colorado Plateau Pinyon-Juniper Shrubland",
    "5602": "Atlantic Coastal Plain Xeric River Dune",
    "5603": "Inter-Mountain Basins Juniper Savanna",
    "5604": "Madrean Juniper Savanna",
    "5605": "Southern Rocky Mountain Ponderosa Pine Savanna",
    "5606": "Southern Rocky Mountain Juniper Woodland and Savanna",
    "5607": "Great Lakes Alvar",
    "5701": "Colorado Plateau Mixed Low Sagebrush Shrubland",
    "5702": "Columbia Plateau Scabland Shrubland",
    "5703": "Inter-Mountain Basins Mat Saltbush Shrubland",
    "5704": "Wyoming Basins Dwarf Sagebrush Shrubland and Steppe",
    "5705": "Great Basin Xeric Mixed Sagebrush Shrubland",
    "5706": "Inter-Mountain Basins Big Sagebrush Shrubland",
    "5707": "Southern Colorado Plateau Sand Shrubland",
    "5801": "Southern Appalachian Grass and Shrub Bald - Shrub Modifier",
    "5802": "Southern Appalachian Grass and Shrub Bald - Herbaceous Modifier",
    "5803": "Colorado Plateau Blackbrush-Mormon-tea Shrubland",
    "5804": "North Pacific Montane Shrubland",
    "5805": "Northwestern Great Plains Shrubland",
    "5806": "Rocky Mountain Lower Montane-Foothill Shrubland",
    "5807": "Northern Atlantic Coastal Plain Heathland and Grassland",
    "5808": "Northern Rocky Mountain Montane-Foothill Deciduous Shrubland",
    "5809": "Rocky Mountain Gambel Oak-Mixed Montane Shrubland",
    "5810": "Western Great Plains Mesquite Woodland and Shrubland",
    "5811": "Edwards Plateau Limestone Shrubland",
    "5812": "Northern Rocky Mountain Subalpine Deciduous Shrubland",
    "7101": "Mediterranean California Alpine Dry Tundra",
    "7102": "Rocky Mountain Alpine Fell-Field",
    "7103": "Rocky Mountain Dry Tundra",
    "7104": "North Pacific Alpine and Subalpine Dry Grassland",
    "7201": "Mediterranean California Subalpine Meadow",
    "7202": "North Pacific Montane Grassland",
    "7203": "Northern Rocky Mountain Lower Montane, Foothill and Valley Grassland",
    "7204": "Northern Rocky Mountain Subalpine-Upper Montane Grassland",
    "7205": "Rocky Mountain Subalpine-Montane Mesic Meadow",
    "7206": "Southern Rocky Mountain Montane-Subalpine Grassland",
    "7301": "Eastern Highland Rim Prairie and Barrens - Dry Modifier",
    "7302": "Central Mixedgrass Prairie",
    "7303": "Chihuahuan Sandy Plains Semi-Desert Grassland",
    "7304": "Columbia Basin Foothill and Canyon Dry Grassland",
    "7305": "Inter-Mountain Basins Semi-Desert Grassland",
    "7306": "Northwestern Great Plains Mixedgrass Prairie",
    "7307": "Columbia Basin Palouse Prairie",
    "7308": "Western Great Plains Foothill and Piedmont Grassland",
    "7309": "Western Great Plains Sand Prairie",
    "7310": "Western Great Plains Shortgrass Prairie",
    "7311": "Western Great Plains Tallgrass Prairie",
    "7312": "North-Central Interior Sand and Gravel Tallgrass Prairie",
    "7313": "Arkansas Valley Prairie and Woodland",
    "7314": "Northern Tallgrass Prairie",
    "7315": "Central Tallgrass Prairie",
    "7316": "Southern Blackland Tallgrass Prairie",
    "7317": "Southeastern Great Plains Tallgrass Prairie",
    "7318": "Florida Dry Prairie",
    "7319": "West Gulf Coastal Plain Northern Calcareous Prairie",
    "7320": "West Gulf Coastal Plain Southern Calcareous Prairie",
    "7321": "East Gulf Coastal Plain Jackson Prairie and Woodland",
    "7322": "Tamaulipan Savanna Grassland",
    "7323": "Tamaulipan Clay Grassland",
    "7324": "South Texas Sand Sheet Grassland",
    "7326": "Chihuahuan Loamy Plains Desert Grassland",
    "7401": "California Mesic Serpentine Grassland",
    "7402": "Great Lakes Wet-Mesic Lakeplain Prairie",
    "7501": "California Central Valley and Southern Coastal Grassland",
    "7502": "California Northern Coastal Grassland",
    "7503": "Atlantic Coastal Plain Southern Dune and Maritime Grassland",
    "7504": "Southwest Florida Dune and Coastal Grassland",
    "7505": "Texas-Louisiana Coastal Prairie",
    "7506": "East Gulf Coastal Plain Dune and Coastal Grassland",
    "7507": "Northern Atlantic Coastal Plain Dune and Swale",
    "7508": "Central and Upper Texas Coast Dune and Coastal Grassland",
    "7509": "South Texas Lomas",
    "7510": "South Texas Dune and Coastal Grassland",
    "7601": "Southern Appalachian Grass and Shrub Bald",
    "7602": "Llano Uplift Acidic Forest, Woodland and Glade",
    "7603": "North Pacific Hypermaritime Shrub and Herbaceous Headland",
    "7604": "North Pacific Herbaceous Bald and Bluff",
    "8101": "Recently Logged Areas",
    "8102": "Successional Shrub/Scrub (Utility Swath)",
    "8103": "Other - Herbaceous",
    "8106": "Harvested forest-tree regeneration",
    "8107": "Harvested forest-shrub regeneration",
    "8108": "Harvested forest-grass/herbaceous regeneration",
    "8201": "Deciduous Plantations",
    "8202": "Evergreen Plantations or Managed Pine (can include dense successional regrowth)",
    "8203": "Managed Tree Plantation",
    "8301": "Recently Burned",
    "8302": "Recently burned forest",
    "8303": "Recently burned grassland",
    "8304": "Recently burned shrubland",
    "8401": "Introduced Upland Vegetation - Treed",
    "8402": "Introduced Upland Vegetation - Shrub",
    "8404": "Introduced Upland Vegetation - Annual Grassland",
    "8406": "Introduced Riparian and Wetland Vegetation",
    "8407": "Introduced Upland Vegetation-Perennial Grassland and Forbland",
    "8408": "Modified/Managed Southern Tall Grassland",
    "8501": "Disturbed, Non-specific",
    "8502": "Recently Chained Pinyon-Juniper Areas",
    "8504": "Ruderal Wetland",
    "9101": "Acadian Salt Marsh and Estuary Systems",
    "9102": "North Pacific Maritime Eelgrass Bed",
    "9103": "Atlantic Coastal Plain Central Salt and Brackish Tidal Marsh",
    "9104": "Atlantic Coastal Plain Indian River Lagoon Tidal Marsh",
    "9105": "Atlantic Coastal Plain Embayed Region Tidal Salt and Brackish Marsh",
    "9106": "Mississippi Sound Salt and Brackish Tidal Marsh",
    "9107": "Mediterranean California Eelgrass Bed",
    "9108": "Temperate Pacific Tidal Salt and Brackish Marsh",
    "9109": "Atlantic Coastal Plain Northern Tidal Salt Marsh",
    "9110": "Florida Big Bend Salt-Brackish Tidal Marsh",
    "9201": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Taxodium Modifier",
    "9202": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Bay/Gum Modifier",
    "9203": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Pine Modifier",
    "9204": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Nupea Modifier",
    "9205": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Clethra Modifier",
    "9206": "Atlantic Coastal Plain Clay-Based Carolina Bay Herbaceous Wetland",
    "9207": "Atlantic Coastal Plain Peatland Pocosin",
    "9208": "Southern Coastal Plain Seepage Swamp and Baygall",
    "9209": "West Gulf Coastal Plain Seepage Swamp and Baygall",
    "9210": "East Gulf Coastal Plain Tidal Wooded Swamp",
    "9211": "Atlantic Coastal Plain Streamhead Seepage Swamp -  Pocosin -  and Baygall",
    "9212": "Central Interior and Appalachian Swamp Systems",
    "9213": "Gulf and Atlantic Coastal Plain Swamp Systems",
    "9214": "Laurentian-Acadian Swamp Systems",
    "9215": "Atlantic Coastal Plain Large Natural Lakeshore",
    "9216": "North Pacific Shrub Swamp",
    "9218": "Atlantic Coastal Plain Southern Tidal Wooded Swamp",
    "9219": "South Florida Everglades Sawgrass Marsh",
    "9220": "Gulf and Atlantic Coastal Plain Tidal Marsh Systems",
    "9221": "Great Lakes Coastal Marsh Systems",
    "9222": "Central Interior and Appalachian Shrub-Herbaceous Wetland Systems",
    "9223": "Floridian Highlands Freshwater Marsh",
    "9224": "Laurentian-Acadian Shrub-Herbaceous Wetland Systems",
    "9225": "Temperate Pacific Freshwater Aquatic Bed",
    "9226": "North Pacific Intertidal Freshwater Wetland",
    "9227": "North American Arid West Emergent Marsh",
    "9228": "Temperate Pacific Freshwater Emergent Marsh",
    "9229": "Great Lakes Freshwater Estuary and Delta",
    "9230": "Atlantic Coastal Plain Embayed Region Tidal Freshwater Marsh",
    "9231": "Central Florida Herbaceous Seep",
    "9232": "Florida Big Bend Fresh-Oligohaline Tidal Marsh",
    "9233": "Atlantic Coastal Plain Northern Fresh and Oligohaline Tidal Marsh",
    "9234": "Northern Great Lakes Coastal Marsh",
    "9235": "Atlantic Coastal Plain Northern Tidal Wooded Swamp",
    "9236": "South Florida Mangrove Swamp",
    "9237": "West Gulf Coastal Plain Near-Coast Large River Swamp",
    "9238": "South Florida Bayhead Swamp",
    "9239": "Southern Coastal Plain Nonriverine Basin Swamp",
    "9240": "Northern Atlantic Coastal Plain Basin Swamp and Wet Hardwood Forest",
    "9241": "Southern Coastal Plain Herbaceous Seepage Bog",
    "9242": "Laurentian-Acadian Freshwater Marsh",
    "9243": "Atlantic Coastal Plain Central Fresh-Oligohaline Tidal Marsh",
    "9301": "Atlantic Coastal Plain Nonriverine Swamp and Wet Hardwood Forest  - Taxodium/Nyssa Modifier",
    "9302": "Atlantic Coastal Plain Nonriverine Swamp and Wet Hardwood Forest - Oak Dominated Modifier",
    "9303": "Atlantic Coastal Plain Clay-Based Carolina Bay Forested Wetland",
    "9304": "Northern Rocky Mountain Conifer Swamp",
    "9305": "South Florida Dwarf Cypress Savanna",
    "9306": "North Pacific Hardwood-Conifer Swamp",
    "9307": "Northern Pacific Mesic Subalpine Woodland",
    "9308": "Laurentian-Acadian Alkaline Conifer-Hardwood Swamp",
    "9401": "Atlantic and Gulf Coastal Plain Interdunal Wetland",
    "9402": "Great Lakes Wooded Dune and Swale",
    "9403": "Inter-Mountain Basins Interdunal Swale Wetland",
    "9501": "Boreal Acidic Peatland Systems",
    "9502": "North Pacific Bog and Fen",
    "9503": "Rocky Mountain Subalpine-Montane Fen",
    "9504": "Mediterranean California Subalpine-Montane Fen",
    "9506": "Southern and Central Appalachian Bog and Fen",
    "9602": "South Florida Wet Marl Prairie",
    "9603": "East Gulf Coastal Plain Savanna and Wet Prairie",
    "9604": "Texas Saline Coastal Prairie",
    "9605": "Eastern Great Plains Wet Meadow, Prairie, and Marsh",
    "9606": "Rocky Mountain Alpine-Montane Wet Meadow",
    "9607": "Willamette Valley Wet Prairie",
    "9608": "Temperate Pacific Montane Wet Meadow",
    "9609": "Columbia Plateau Silver Sagebrush Seasonally Flooded Shrub-Steppe",
    "9610": "Chihuahuan-Sonoran Desert Bottomland and Swale Grassland",
    "9701": "Lower Mississippi River Bottomland Depressions - Forest Modifier",
    "9702": "South Florida Cypress Dome",
    "9703": "Southern Coastal Plain Nonriverine Cypress Dome",
    "9704": "Northern Rocky Mountain Wooded Vernal Pool",
    "9705": "Great Plains Prairie Pothole",
    "9706": "Western Great Plains Depressional Wetland Systems",
    "9707": "Western Great Plains Open Freshwater Depression Wetland",
    "9708": "Columbia Plateau Vernal Pool",
    "9709": "Northern California Claypan Vernal Pool",
    "9710": "Western Great Plains Closed Depression Wetland",
    "9711": "Western Great Plains Saline Depression Wetland",
    "9712": "Central Florida Herbaceous Pondshore",
    "9713": "East Gulf Coastal Plain Southern Depression Pondshore",
    "9714": "Inter-Mountain Basins Alkaline Closed Depression",
    "9715": "Southern Piedmont/Ridge and Valley Upland Depression Swamp",
    "9716": "Atlantic Coastal Plain Depression Pondshore",
    "9717": "Mississippi River Bottomland Depression",
    "9718": "South Florida Freshwater Slough and Gator Hole",
    "9801": "Atlantic Coastal Plain Blackwater Stream Floodplain Forest - Forest Modifier",
    "9802": "Central Appalachian Floodplain - Forest Modifier",
    "9803": "Central Appalachian Riparian - Forest Modifier",
    "9804": "East Gulf Coastal Plain Large River Floodplain Forest - Forest Modifier",
    "9805": "South-Central Interior Large Floodplain - Forest Modifier",
    "9806": "Southern Piedmont Large Floodplain Forest - Forest Modifier",
    "9807": "East Gulf Coastal Plain Large River Floodplain Forest - Herbaceous Modifier",
    "9808": "South-Central Interior Large Floodplain - Herbaceous Modifier",
    "9809": "California Central Valley Riparian Woodland and Shrubland",
    "9810": "Inter-Mountain Basins Greasewood Flat",
    "9811": "North Pacific Lowland Riparian Forest and Shrubland",
    "9812": "North Pacific Montane Riparian Woodland and Shrubland",
    "9813": "Rocky Mountain Montane Riparian Systems",
    "9814": "Western Great Plains Floodplain Systems",
    "9815": "Eastern Boreal Floodplain",
    "9816": "Tamaulipan Floodplain",
    "9817": "Eastern Great Plains Floodplain Systems",
    "9818": "Central Interior and Appalachian Floodplain Systems",
    "9819": "Central Interior and Appalachian Riparian Systems",
    "9820": "Laurentian-Acadian Floodplain Systems",
    "9821": "Tamaulipan Riparian Systems",
    "9822": "North American Warm Desert Wash",
    "9823": "Western Great Plains Floodplain",
    "9824": "Northern Rocky Mountain Lower Montane Riparian Woodland and Shrubland",
    "9825": "Rocky Mountain Lower Montane Riparian Woodland and Shrubland",
    "9826": "Northwestern Great Plains Floodplain",
    "9827": "Mississippi River Riparian Forest",
    "9828": "Cumberland Riverscour",
    "9829": "Edwards Plateau Riparian",
    "9830": "Great Basin Foothill and Lower Montane Riparian Woodland and Shrubland",
    "9831": "Columbia Basin Foothill Riparian Woodland and Shrubland",
    "9832": "Rocky Mountain Subalpine-Montane Riparian Woodland",
    "9833": "North American Warm Desert Lower Montane Riparian Woodland and Shrubland",
    "9834": "North American Warm Desert Riparian Mesquite Bosque",
    "9835": "North American Warm Desert Riparian Woodland and Shrubland",
    "9836": "Mississippi River Low Floodplain (Bottomland) Forest",
    "9837": "Rocky Mountain Subalpine-Montane Riparian Shrubland",
    "9838": "Southern Coastal Plain Hydric Hammock",
    "9839": "West Gulf Coastal Plain Small Stream and River Forest",
    "9840": "West Gulf Coastal Plain Large River Floodplain Forest",
    "9841": "Southern Piedmont Small Floodplain and Riparian Forest",
    "9842": "Atlantic Coastal Plain Small Brownwater River Floodplain Forest",
    "9843": "Atlantic Coastal Plain Small Blackwater River Floodplain Forest",
    "9844": "Red River Large Floodplain Forest",
    "9845": "Atlantic Coastal Plain Brownwater Stream Floodplain Forest",
    "9846": "Mediterranean California Serpentine Foothill and Lower Montane Riparian Woodland and Seep",
    "9847": "Northwestern Great Plains Riparian",
    "9848": "Western Great Plains Riparian Woodland and Shrubland",
    "9849": "Mediterranean California Foothill and Lower Montane Riparian Woodland",
    "9850": "South-Central Interior Small Stream and Riparian",
    "9851": "East Gulf Coastal Plain Small Stream and River Floodplain Forest",
    "9852": "Southern Coastal Plain Blackwater River Floodplain Forest",
    "9853": "Texas-Louisiana Coastal Prairie Slough",
    "9854": "Mississippi River Floodplain and Riparian Forest",
    "9855": "Inter-Mountain Basins Montane Riparian Systems",
    "9856": "North American Warm Desert Riparian Systems",
    "9857": "South-Central Interior Large Floodplain",
    "9858": "Ozark-Ouachita Riparian",
    "9901": "East Gulf Coastal Plain Jackson Plain Dry Flatwoods - Open Understory Modifier",
    "9902": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Offsite Hardwood Modifier",
    "9903": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Open Understory Modifier",
    "9904": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Scrub/Shrub Understory Modifier",
    "9905": "South Florida Pine Flatwoods",
    "9906": "Central Atlantic Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "9907": "Atlantic Coastal Plain Southern Wet Pine Savanna and Flatwoods",
    "9908": "West Gulf Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "9909": "Central Florida Pine Flatwoods",
    "9911": "East Gulf Coastal Plain Southern Loblolly-Hardwood Flatwoods",
    "9912": "South-Central Interior / Upper Coastal Plain Wet Flatwoods",
    "9913": "West Gulf Coastal Plain Pine-Hardwood Flatwoods",
    "9914": "North-Central Interior Wet Flatwoods",
    "9915": "Lower Mississippi River Flatwoods",
    "9916": "West Gulf Coastal Plain Nonriverine Wet Hardwood Flatwoods"
  },
  "LANDFIREFuelModel40": {
    "91": "NB1",
    "92": "NB2",
    "93": "NB3",
    "98": "NB8",
    "99": "NB9",
    "101": "GR1",
    "102": "GR2",
    "103": "GR3",
    "104": "GR4",
    "105": "GR5",
    "106": "GR6",
    "107": "GR7",
    "108": "GR8",
    "109": "GR9",
    "121": "GS1",
    "122": "GS2",
    "123": "GS3",
    "124": "GS4",
    "141": "SH1",
    "142": "SH2",
    "143": "SH3",
    "144": "SH4",
    "145": "SH5",
    "146": "SH6",
    "147": "SH7",
    "148": "SH8",
    "149": "SH9",
    "161": "TU1",
    "162": "TU2",
    "163": "TU3",
    "164": "TU4",
    "165": "TU5",
    "181": "TL1",
    "182": "TL2",
    "183": "TL3",
    "184": "TL4",
    "185": "TL5",
    "186": "TL6",
    "187": "TL7",
    "188": "TL8",
    "189": "TL9",
    "201": "SB1",
    "202": "SB2",
    "203": "SB3",
    "204": "SB4"
  },
  "landcover-2005-NALCMS": {
    "1": "Temperate or sub-polar needleleaf forest",
    "2": "Sub-polar taiga needleleaf forest",
    "3": "Tropical or sub-tropical broadleaf evergreen forest",
    "4": "Tropical or sub-tropical broadleaf deciduous forest",
    "5": "Temperate or sub-polar broadleaf deciduous forest",
    "6": "Mixed forest",
    "7": "Tropical or sub-tropical shrubland",
    "8": "Temperate or sub-polar shrubland",
    "9": "Tropical or sub-tropical grassland",
    "10": "Temperate or sub-polar grassland",
    "11": "Sub-polar or polar shrubland-lichen-moss",
    "12": "Sub-polar or polar grassland-lichen-moss",
    "13": "Sub-polar or polar barren-lichen-moss",
    "14": "Wetland",
    "15": "Cropland",
    "16": "Barren land",
    "17": "Urban and built-up",
    "18": "Water",
    "19": "Snow and ice"
  },
  "landcover-2010-NALCMS": {
    "1": "Temperate or sub-polar needleleaf forest",
    "2": "Sub-polar taiga needleleaf forest",
    "3": "Tropical or sub-tropical broadleaf evergreen forest",
    "4": "Tropical or sub-tropical broadleaf deciduous forest",
    "5": "Temperate or sub-polar broadleaf deciduous forest",
    "6": "Mixed forest",
    "7": "Tropical or sub-tropical shrubland",
    "8": "Temperate or sub-polar shrubland",
    "9": "Tropical or sub-tropical grassland",
    "10": "Temperate or sub-polar grassland",
    "11": "Sub-polar or polar shrubland-lichen-moss",
    "12": "Sub-polar or polar grassland-lichen-moss",
    "13": "Sub-polar or polar barren-lichen-moss",
    "14": "Wetland",
    "15": "Cropland",
    "16": "Barren land",
    "17": "Urban and built-up",
    "18": "Water",
    "19": "Snow and ice"
  },
  "CropLands2013": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "51": "Chick Peas",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "63": "Forest",
    "64": "Shrubland",
    "65": "Barren",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "81": "Clouds/No Data",
    "82": "Developed",
    "83": "Water",
    "87": "Wetlands",
    "88": "Nonag_Undefined",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "210": "Prunes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  },
  "CropLands2015": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "51": "Chick Peas",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "63": "Forest",
    "64": "Shrubland",
    "65": "Barren",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "81": "Clouds/No Data",
    "82": "Developed",
    "83": "Water",
    "87": "Wetlands",
    "88": "Nonag/Undefined",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "210": "Prunes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  },
  "CropLands2014": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "51": "Chick Peas",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "63": "Forest",
    "64": "Shrubland",
    "65": "Barren",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "81": "Clouds/No Data",
    "82": "Developed",
    "83": "Water",
    "87": "Wetlands",
    "88": "Nonag/Undefined",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "210": "Prunes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  }
}
