var legend_lookup = {
  "forest-type": {
    "1": "Jack Pine",
    "2": "Red Pine",
    "3": "Eastern White Pine",
    "4": "Eastern White Pine/Eastern Hemlock",
    "5": "Eastern Hemlock",
    "6": "Balsam Fir",
    "7": "White Spruce",
    "8": "Red Spruce",
    "9": "Red Spruce/Balsam Fir",
    "10": "Black Spruce",
    "11": "Tamarack",
    "12": "Northern White-cedar",
    "13": "Longleaf Pine",
    "14": "Slash Pine",
    "15": "Loblolly Pine",
    "16": "Shortleaf Pine",
    "17": "Virginia Pine",
    "18": "Sand Pine",
    "19": "Table-mountain Pine",
    "20": "Pond Pine",
    "21": "Pitch Pine",
    "22": "Spruce Pine",
    "23": "Eastern Redcedar",
    "24": "Rocky Mountain Juniper",
    "25": "Western Juniper",
    "26": "Juniper Woodland",
    "27": "Pinyon Juniper Woodland",
    "28": "Douglas-fir",
    "29": "Port-orford-cedar",
    "30": "Ponderosa Pine",
    "31": "Jeffrey Pine/Coulter Pine/Bigcon",
    "32": "Sugar Pine",
    "33": "Western White Pine",
    "34": "White Fir",
    "35": "Red Fir",
    "36": "Noble Fir",
    "37": "Pacific Silver Fir",
    "38": "Engelmann Spruce",
    "39": "Engelmann Spruce/Subalpine Fir",
    "40": "Grand Fir",
    "41": "Subalpine Fir",
    "42": "Blue Spruce",
    "43": "Mountain Hemlock",
    "44": "Alaska-yellow-cedar",
    "45": "Lodgepole Pine",
    "46": "Western Hemlock",
    "47": "Western Redcedar",
    "48": "Sitka Spruce",
    "49": "Western Larch",
    "50": "Redwood",
    "51": "Giant Sequoia",
    "52": "Knobcone Pine",
    "53": "Foxtail Pine/Bristlecone Pine",
    "54": "Limber Pine",
    "55": "Whitebark Pine",
    "56": "Misc. Western Softwoods",
    "57": "California Mixed Conifer",
    "58": "Scotch Pine",
    "59": "Other Exotic Softwoods",
    "60": "Norway Spruce",
    "61": "Eastern White Pine/Northern Red",
    "62": "Eastern Redcedar/Hardwood",
    "63": "Longleaf Pine/Oak",
    "64": "Shortleaf Pine/Oak",
    "65": "Virginia Pine/Southern Red Oak",
    "66": "Loblolly Pine/Hardwood",
    "67": "Slash Pine/Hardwood",
    "68": "Other Pine/Hardwood",
    "69": "Post Oak/Blackjack Oak",
    "70": "Chestnut Oak",
    "71": "White Oak/Red Oak/Hickory",
    "72": "White Oak",
    "73": "Northern Red Oak",
    "74": "Yellow-poplar/White Oak/Northern",
    "75": "Sassafras/Persimmon",
    "76": "Sweetgum/Yellow-poplar",
    "77": "Bur Oak",
    "78": "Scarlet Oak",
    "79": "Yellow-poplar",
    "80": "Black Walnut",
    "81": "Black Locust",
    "82": "Southern Scrub Oak",
    "83": "Chestnut Oak/Black Oak/Scarlet O",
    "84": "Red Maple/Oak",
    "85": "Mixed Upland Hardwoods",
    "86": "Swamp Chestnut Oak/Cherrybark Oa",
    "87": "Sweetgum/Nuttall Oak/Willow Oak",
    "88": "Overcup Oak/Water Hickory",
    "89": "Atlantic White-cedar",
    "90": "Baldcypress/Water Tupelo",
    "91": "Sweetbay/Swamp Tupelo/Red Maple",
    "92": "Black Ash/American Elm/Red Maple",
    "93": "River Birch/Sycamore",
    "94": "Cottonwood",
    "95": "Willow",
    "96": "Sycamore/Pecan/American Elm",
    "97": "Sugarberry/Hackberry/Elm/Green A",
    "98": "Silver Maple/American Elm",
    "99": "Red Maple/Lowland",
    "100": "Cottonwood/Willow",
    "101": "Oregon Ash",
    "102": "Sugar Maple/Beech/Yellow Birch",
    "103": "Black Cherry",
    "104": "Cherry/Ash/Yellow-poplar",
    "105": "Hard Maple/Basswood",
    "106": "Elm/Ash/Locust",
    "107": "Red Maple/Upland",
    "108": "Aspen",
    "109": "Paper Birch",
    "110": "Gray Birch",
    "111": "Balsam Poplar",
    "112": "Red Alder",
    "113": "Bigleaf Maple",
    "114": "Gray Pine",
    "115": "California Black Oak",
    "116": "Oregon White Oak",
    "117": "Blue Oak",
    "118": "Deciduous Oak Woodland",
    "119": "Evergreen Oak",
    "120": "Coast Live Oak",
    "121": "Canyon Live Oak/Interior Live Oa",
    "122": "Tanoak",
    "123": "California Laurel",
    "124": "Giant Chinkapin",
    "125": "Pacific Madrone",
    "126": "Mesquite Woodland",
    "127": "Cerocarpus Woodland",
    "128": "Intermountain Maple Woodland",
    "129": "Misc. Western Hardwood Woodlands",
    "130": "Sable Palm",
    "131": "Mangrove",
    "132": "Eucalyptus"
  },
  "forest-group": {
    "28": "White/Red/Jack Pine Group",
    "22": "Spruce/Fir Group",
    "12": "Longleaf/Slash Pine Group",
    "10": "Loblolly/Shortleaf Pine Group",
    "19": "Pinyon/Juniper Group",
    "4": "Douglas-fir Group",
    "20": "Ponderosa Pine Group",
    "27": "Western White Pine Group",
    "8": "Fir/Spruce/Mountain Hemlock Grou",
    "11": "Lodgepole Pine Group",
    "9": "Hemlock/Sitka Spruce Group",
    "25": "Western Larch Group",
    "21": "Redwood Group",
    "18": "Other Western Softwoods Group",
    "3" : "California Mixed Conifer Group",
    "7" : "Exotic Softwoods Group",
    "16": "Oak/Pine Group",
    "15": "Oak/Hickory Group",
    "14": "Oak/Gum/Cypress Group",
    "5": "Elm/Ash/Cottonwood Group",
    "13": "Maple/Beech/Birch Group",
    "2": "Aspen/Birch Group",
    "1": "Alder/Maple Group",
    "26": "Western Oak Group",
    "23": "Tanoak/Laurel Group",
    "17": "Other Western Hardwoods Group",
    "24": "Tropical Hardwoods Group",
    "6": "Exotic Hardwoods Group"
  },
  "nlcd-2006": {
    "11": "Open Water",
    "12": "Perennial Snow/Ice",
    "21": "Developed, Open Space",
    "22": "Developed, Low Intensity",
    "23": "Developed, Medium Intensity",
    "24": "Developed, High Intensity",
    "31": "Barren Land",
    "41": "Deciduous Forest",
    "42": "Evergreen Forest",
    "43": "Mixed Forest",
    "52": "Shrub/Scrub",
    "71": "Herbaceuous",
    "81": "Hay/Pasture",
    "82": "Cultivated Crops",
    "90": "Woody Wetlands",
    "95": "Emergent Herbaceuous Wetlands"
  },
  "gapnat-2001": {
    "1201": "Developed, Open Space",
    "1202": "Developed, Low Intensity",
    "1203": "Developed, Medium Intensity",
    "1204": "Developed, High Intensity",
    "1301": "Quarries, Mines, Gravel Pits and Oil Wells",
    "1401": "Orchards Vineyards and Other High Structure Agriculture",
    "1402": "Cultivated Cropland",
    "1403": "Pasture/Hay",
    "2102": "Open Water (Fresh)",
    "2103": "Open Water (Brackish/Salt)",
    "2104": "Open Water (Aquaculture)",
    "3105": "Undifferentiated Barren Land",
    "3106": "Atlantic Coastal Plain Northern Sandy Beach",
    "3107": "Atlantic Coastal Plain Southern Beach",
    "3110": "Unconsolidated Shore",
    "3111": "North American Warm Desert Active and Stabilized Dune",
    "3112": "Northern Atlantic Coastal Plain Sandy Beach",
    "3113": "Upper Texas Coast Beach",
    "3114": "Louisiana Beach",
    "3115": "Southeast Florida Beach",
    "3116": "Great Lakes Dune",
    "3117": "South Florida Shell Hash Beach",
    "3118": "Florida Panhandle Beach Vegetation",
    "3119": "Atlantic Coastal Plain Sea Island Beach",
    "3120": "Southwest Florida Beach",
    "3121": "Inter-Mountain Basins Active and Stabilized Dune",
    "3122": "Mediterranean California Southern Coastal Dune",
    "3123": "Mediterranean California Northern Coastal Dune",
    "3124": "North Pacific Maritime Coastal Sand Dune and Strand",
    "3125": "Texas Coastal Bend Beach",
    "3201": "North American Warm Desert Bedrock Cliff and Outcrop",
    "3202": "Rocky Mountain Cliff, Canyon and Massive Bedrock",
    "3203": "Western Great Plains Cliff and Outcrop",
    "3204": "Great Lakes Acidic Rocky Shore and Cliff",
    "3205": "Central Interior Calcareous Cliff and Talus",
    "3206": "Central Interior Acidic Cliff and Talus",
    "3207": "North-Central Appalachian Circumneutral Cliff and Talus",
    "3208": "North-Central Appalachian Acidic Cliff and Talus",
    "3209": "North Pacific Montane Massive Bedrock, Cliff and Talus",
    "3210": "Southern Piedmont Cliff",
    "3211": "North Pacific Coastal Cliff and Bluff",
    "3212": "Southern California Coast Ranges Cliff and Canyon",
    "3213": "Central California Coast Ranges Cliff and Canyon",
    "3214": "Klamath-Siskiyou Cliff and Outcrop",
    "3215": "Sierra Nevada Cliff and Canyon",
    "3216": "Inter-Mountain Basins Cliff and Canyon",
    "3217": "Southwestern Great Plains Canyon",
    "3218": "Colorado Plateau Mixed Bedrock Canyon and Tableland",
    "3219": "Southern Interior Acid Cliff",
    "3220": "Southern Appalachian Montane Cliff",
    "3221": "Southern Interior Calcareous Cliff",
    "3301": "Western Great Plains Badland",
    "3302": "East Gulf Coastal Plain Dry Chalk Bluff",
    "3303": "North American Warm Desert Badland",
    "3304": "Inter-Mountain Basins Shale Badland",
    "3305": "Mediterranean California Coastal Bluff",
    "3306": "Columbia Plateau Ash and Tuff Badland",
    "3401": "Temperate Pacific Intertidal Mudflat",
    "3402": "Temperate Pacific Freshwater Mudflat",
    "3403": "Inter-Mountain Basins Wash",
    "3404": "North Pacific Serpentine Barren",
    "3405": "North American Warm Desert Playa",
    "3406": "Mediterranean California Serpentine Barrens",
    "3407": "Inter-Mountain Basins Playa",
    "3501": "North Pacific Alpine and Subalpine Bedrock and Scree",
    "3502": "North American Alpine Ice Field",
    "3503": "Rocky Mountain Alpine Bedrock and Scree",
    "3504": "Mediterranean California Alpine Bedrock and Scree",
    "3506": "Southern Appalachian Rocky Summit",
    "3601": "Geysers and Hot Springs",
    "3602": "Southern Appalachian Granitic Dome",
    "3603": "Inter-Mountain Basins Volcanic Rock and Cinder Land",
    "3604": "North Pacific Volcanic Rock and Cinder Land",
    "3605": "North American Warm Desert Pavement",
    "3606": "Southern Piedmont Granite Flatrock",
    "3607": "North American Warm Desert Volcanic Rockland",
    "4101": "Central and Southern Appalachian Northern Hardwood Forest",
    "4102": "East Gulf Coastal Plain Limestone Forest",
    "4103": "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland - Hardwood Modifier",
    "4104": "Northeastern Interior Dry Oak Forest-Hardwood Modifier",
    "4105": "East Gulf Coastal Plain Northern Loess Plain Oak-Hickory Upland - Juniper Modifier",
    "4106": "Northeastern Interior Dry Oak Forest - Mixed Modifier",
    "4107": "Ridge and Valley Calcareous Valley Bottom Glade and Woodland",
    "4108": "East Gulf Coastal Plain Black Belt Calcareous Prairie and Woodland - Herbaceous Modifier",
    "4109": "Southern and Central Appalachian Oak Forest - Xeric",
    "4110": "North Pacific Oak Woodland",
    "4111": "Rocky Mountain Aspen Forest and Woodland",
    "4112": "Rocky Mountain Bigtooth Maple Ravine Woodland",
    "4113": "Laurentian-Acadian Northern Hardwoods Forest",
    "4114": "Northeastern Interior Dry-Mesic Oak Forest",
    "4115": "Ozark-Ouachita Dry-Mesic Oak Forest",
    "4116": "Southern Interior Low Plateau Dry-Mesic Oak Forest",
    "4117": "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest",
    "4118": "Crosstimbers Oak Forest and Woodland",
    "4119": "Southern Appalachian Northern Hardwood Forest",
    "4120": "North-Central Interior Dry-Mesic Oak Forest and Woodland",
    "4121": "North-Central Interior Dry Oak Forest and Woodland",
    "4122": "Ouachita Montane Oak Forest",
    "4123": "North-Central Interior Beech-Maple Forest",
    "4124": "North-Central Interior Maple-Basswood Forest",
    "4125": "Southern and Central Appalachian Oak Forest",
    "4126": "Allegheny-Cumberland Dry Oak Forest and Woodland - Hardwood",
    "4127": "Central and Southern Appalachian Montane Oak Forest",
    "4128": "East Gulf Coastal Plain Northern Loess Bluff Forest",
    "4129": "East Gulf Coastal Plain Southern Loess Bluff Forest",
    "4130": "Southern Coastal Plain Dry Upland Hardwood Forest",
    "4131": "Eastern Great Plains Tallgrass Aspen Parkland",
    "4132": "South Florida Hardwood Hammock",
    "4133": "Atlantic Coastal Plain Dry and Dry-Mesic Oak Forest",
    "4134": "Southwest Florida Coastal Strand and Maritime Hammock",
    "4135": "Southeast Florida Coastal Strand and Maritime Hammock",
    "4136": "Central and South Texas Coastal Fringe Forest and Woodland",
    "4137": "West Gulf Coastal Plain Chenier and Upper Texas Coastal Fringe Forest and Woodland",
    "4138": "Northwestern Great Plains Aspen Forest and Parkland",
    "4139": "Mississippi River Alluvial Plain Dry-Mesic Loess Slope Forest",
    "4140": "East-Central Texas Plains Post Oak Savanna and Woodland",
    "4141": "East-Central Texas Plains Riparian Forest",
    "4142": "East-Central Texas Plains Floodplain Forest",
    "4143": "Madrean Encinal",
    "4144": "Mediterranean California Mixed Oak Woodland",
    "4145": "South Florida Pine Rockland",
    "4146": "Southern Coastal Plain Oak Dome and Hammock",
    "4147": "Inter-Mountain Basins Curl-leaf Mountain Mahogany Woodland and Shrubland",
    "4148": "North Pacific Broadleaf Landslide Forest and Shrubland",
    "4149": "Ozark-Ouachita Dry Oak Woodland",
    "4150": "East Gulf Coastal Plain Maritime Forest",
    "4151": "Lower Mississippi River Dune Woodland and Forest",
    "4152": "Edwards Plateau Limestone Savanna and Woodland",
    "4153": "Mississippi Delta Maritime Forest",
    "4154": "Western Great Plains Wooded Draw and Ravine",
    "4155": "Edwards Plateau Dry-Mesic Slope Forest and Woodland",
    "4201": "Boreal Aspen-Birch Forest",
    "4202": "Southern Piedmont Mesic Forest",
    "4203": "Southern Crowley's Ridge Mesic Loess Slope Forest",
    "4204": "West Gulf Coastal Plain Mesic Hardwood Forest",
    "4205": "East Gulf Coastal Plain Northern Mesic Hardwood Forest",
    "4206": "South-Central Interior/Upper Coastal Plain Wet Flatwoods",
    "4207": "Ozark-Ouachita Mesic Hardwood Forest",
    "4208": "Edwards Plateau Mesic Canyon",
    "4209": "East Gulf Coastal Plain Southern Mesic Slope Forest",
    "4210": "Atlantic Coastal Plain Central Maritime Forest",
    "4211": "Atlantic Coastal Plain Northern Maritime Forest",
    "4212": "Atlantic Coastal Plain Southern Maritime Forest",
    "4301": "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest - Hardwood Modifier",
    "4302": "Southern Piedmont Dry Oak-(Pine) Forest - Hardwood Modifier",
    "4303": "East Gulf Coastal Plain Black Belt Calcareous Prairie and Woodland - Woodland Modifier",
    "4304": "Northeastern Interior Dry Oak Forest - Virginia/Pitch Pine Modifier",
    "4305": "Southern Piedmont Dry Oak-(Pine) Forest - Loblolly Pine Modifier",
    "4306": "East Gulf Coastal Plain Northern Dry Upland Hardwood Forest - Offsite Pine Modifier",
    "4307": "Allegheny-Cumberland Dry Oak Forest and Woodland - Pine Modifier",
    "4308": "Southern Ridge and Valley Dry Calcareous Forest - Pine modifier",
    "4309": "East Gulf Coastal Plain Interior Shortleaf Pine-Oak Forest - Mixed Modifier",
    "4310": "Southern Piedmont Dry Oak-(Pine) Forest - Mixed Modifier",
    "4312": "Western Great Plains Dry Bur Oak Forest and Woodland",
    "4313": "Northern Atlantic Coastal Plain Dry Hardwood Forest",
    "4314": "Appalachian Shale Barrens",
    "4315": "Madrean Pine-Oak Forest and Woodland",
    "4316": "Madrean Upper Montane Conifer-Oak Forest and Woodland",
    "4317": "Mediterranean California Lower Montane Black Oak-Conifer Forest and Woodland",
    "4318": "Mediterranean California Red Fir Forest",
    "4319": "North Pacific Dry Douglas-fir-(Madrone) Forest and Woodland",
    "4320": "Mediterranean California Mixed Evergreen Forest",
    "4321": "West Gulf Coastal Plain Upland Longleaf Pine Forest and Woodland",
    "4322": "Southeastern Interior Longleaf Pine Woodland",
    "4323": "Laurentian-Acadian Northern Pine-(Oak) Forest",
    "4324": "Inter-Mountain Basins Aspen-Mixed Conifer Forest and Woodland",
    "4325": "Central Interior Highlands Dry Acidic Glade and Barrens",
    "4326": "Boreal White Spruce-Fir-Hardwood Forest",
    "4327": "Laurentian-Acadian Pine-Hemlock-Hardwood Forest",
    "4328": "Ozark-Ouachita Shortleaf Pine-Oak Forest and Woodland",
    "4329": "Southern Piedmont Dry Oak-(Pine) Forest",
    "4330": "Central Appalachian Oak and Pine Forest",
    "4331": "Appalachian Hemlock-Hardwood Forest",
    "4332": "West Gulf Coastal Plain Pine-Hardwood Forest",
    "4333": "Acadian Low-Elevation Spruce-Fir-Hardwood Forest",
    "4334": "Southern Ridge and Valley Dry Calcareous Forest",
    "4335": "Central Appalachian Pine-Oak Rocky Woodland",
    "4336": "West Gulf Coastal Plain Sandhill Oak and Shortleaf Pine Forest and Woodland",
    "4337": "Northern Crowley's Ridge Sand Forest",
    "4338": "North Pacific Lowland Mixed Hardwood-Conifer Forest and Woodland",
    "4401": "Southern and Central Appalachian Cove Forest",
    "4402": "South-Central Interior Mesophytic Forest",
    "4403": "Atlantic Coastal Plain Mesic Hardwood and Mixed Forest",
    "4404": "Mediterranean California Mesic Serpentine Woodland and Chaparral",
    "4501": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Offsite Hardwood Modifier",
    "4502": "Florida Longleaf Pine Sandhill- Open Understory Modifier",
    "4503": "Florida Longleaf Pine Sandhill - Scrub/Shrub Understory Modifier",
    "4504": "Atlantic Coastal Plain Fall-Line Sandhills Longleaf Pine Woodland - Loblolly Modifier",
    "4505": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Open Understory",
    "4506": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Scrub/Shrub Understory",
    "4507": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Loblolly Modifier",
    "4508": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Open Understory Modifier",
    "4509": "East Gulf Coastal Plain Interior Upland Longleaf Pine Woodland - Scrub/Shrub Modifier",
    "4510": "Northern Rocky Mountain Western Larch Savanna",
    "4511": "Central and Southern California Mixed Evergreen Woodland",
    "4512": "Colorado Plateau Pinyon-Juniper Woodland",
    "4513": "Columbia Plateau Western Juniper Woodland and Savanna",
    "4514": "Great Basin Pinyon-Juniper Woodland",
    "4515": "Inter-Mountain Basins Subalpine Limber-Bristlecone Pine Woodland",
    "4516": "Klamath-Siskiyou Lower Montane Serpentine Mixed Conifer Woodland",
    "4517": "Klamath-Siskiyou Upper Montane Serpentine Mixed Conifer Woodland",
    "4518": "Madrean Pinyon-Juniper Woodland",
    "4519": "Mediterranean California Dry-Mesic Mixed Conifer Forest and Woodland",
    "4520": "California Montane Jeffrey Pine-(Ponderosa Pine) Woodland",
    "4521": "Mediterranean California Subalpine Woodland",
    "4522": "North Pacific Maritime Dry-Mesic Douglas-fir-Western Hemlock Forest",
    "4523": "North Pacific Mountain Hemlock Forest",
    "4524": "Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest",
    "4525": "Northern Rocky Mountain Subalpine Woodland and Parkland",
    "4526": "Rocky Mountain Foothill Limber Pine-Juniper Woodland",
    "4527": "Rocky Mountain Lodgepole Pine Forest",
    "4528": "Southern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest and Woodland",
    "4529": "Northern Rocky Mountain Ponderosa Pine Woodland and Savanna",
    "4530": "Southern Rocky Mountain Ponderosa Pine Woodland",
    "4531": "Rocky Mountain Subalpine Dry-Mesic Spruce-Fir Forest and Woodland",
    "4532": "Rocky Mountain Subalpine-Montane Limber-Bristlecone Pine Woodland",
    "4533": "Sierra Nevada Subalpine Lodgepole Pine Forest and Woodland",
    "4534": "Southern Rocky Mountain Pinyon-Juniper Woodland",
    "4535": "Boreal Jack Pine-Black Spruce Forest",
    "4536": "Atlantic Coastal Plain Upland Longleaf Pine Woodland",
    "4537": "Southern Appalachian Montane Pine Forest and Woodland",
    "4538": "Southern Appalachian Low Mountain Pine Forest",
    "4539": "Northeastern Interior Pine Barrens",
    "4540": "Northern Atlantic Coastal Plain Pitch Pine Barrens",
    "4541": "East-Central Texas Plains Pine Forest and Woodland",
    "4542": "Laurentian Jack Pine-Red Pine Forest",
    "4543": "Middle Rocky Mountain Montane Douglas-fir Forest and Woodland",
    "4544": "Rocky Mountain Poor-Site Lodgepole Pine Forest",
    "4545": "California Coastal Closed-Cone Conifer Forest and Woodland",
    "4546": "Sierran-Intermontane Desert Western White Pine-White Fir Woodland",
    "4547": "North Pacific Dry-Mesic Silver Fir-Western Hemlock-Douglas-fir Forest",
    "4548": "Northwestern Great Plains - Black Hills Ponderosa Pine Woodland and Savanna",
    "4549": "Ozark-Ouachita Shortleaf Pine-Bluestem Woodland",
    "4550": "East Cascades Oak-Ponderosa Pine Forest and Woodland",
    "4551": "Acadian-Appalachian Montane Spruce-Fir Forest",
    "4552": "North Pacific Wooded Volcanic Flowage",
    "4553": "Atlantic Coastal Plain Fall-line Sandhills Longleaf Pine Woodland - Offsite Hardwood",
    "4601": "California Coastal Redwood Forest",
    "4602": "East Cascades Mesic Montane Mixed-Conifer Forest and Woodland",
    "4603": "Mediterranean California Mesic Mixed Conifer Forest and Woodland",
    "4604": "North Pacific Hypermaritime Sitka Spruce Forest",
    "4605": "North Pacific Maritime Mesic Subalpine Parkland",
    "4606": "North Pacific Maritime Mesic-Wet Douglas-fir-Western Hemlock Forest",
    "4607": "North Pacific Mesic Western Hemlock-Silver Fir Forest",
    "4608": "Northern California Mesic Subalpine Woodland",
    "4609": "Northern Rocky Mountain Mesic Montane Mixed Conifer Forest",
    "4610": "Southern Rocky Mountain Mesic Montane Mixed Conifer Forest and Woodland",
    "4611": "Rocky Mountain Subalpine Mesic Spruce-Fir Forest and Woodland",
    "4612": "Central and Southern Appalachian Spruce-Fir Forest",
    "4613": "North Pacific Hypermaritime Western Red-cedar-Western Hemlock Forest",
    "5101": "Mediterranean California Alpine Fell-Field",
    "5102": "North Pacific Dry and Mesic Alpine Dwarf-Shrubland, Fell-field and Meadow",
    "5103": "Rocky Mountain Alpine Dwarf-Shrubland",
    "5104": "Rocky Mountain Alpine Tundra/Fell-field/Dwarf-shrub Map Unit",
    "5105": "Acadian-Appalachian Alpine Tundra",
    "5106": "North Pacific Avalanche Chute Shrubland",
    "5107": "Acadian-Appalachian Subalpine Woodland and Heath-Krummholz",
    "5201": "Chihuahuan Creosotebush, Mixed Desert and Thorn Scrub",
    "5202": "Chihuahuan Mixed Salt Desert Scrub",
    "5203": "Chihuahuan Stabilized Coppice Dune and Sand Flat Scrub",
    "5204": "Chihuahuan Succulent Desert Scrub",
    "5205": "Inter-Mountain Basins Mixed Salt Desert Scrub",
    "5206": "Mojave Mid-Elevation Mixed Desert Scrub",
    "5207": "Sonora-Mojave Creosotebush-White Bursage Desert Scrub",
    "5208": "Sonora-Mojave Mixed Salt Desert Scrub",
    "5209": "Sonoran Mid-Elevation Desert Scrub",
    "5210": "Southern California Coastal Scrub",
    "5211": "Apacherian-Chihuahuan Mesquite Upland Scrub",
    "5212": "Chihuahuan Mixed Desert and Thorn Scrub",
    "5213": "Sonoran Paloverde-Mixed Cacti Desert Scrub",
    "5214": "Florida Peninsula Inland Scrub",
    "5215": "Tamaulipan Mixed Deciduous Thornscrub",
    "5216": "Tamaulipan Mesquite Upland Scrub",
    "5217": "Tamaulipan Calcareous Thornscrub",
    "5218": "Northern California Coastal Scrub",
    "5301": "Western Great Plains Sandhill Steppe",
    "5302": "Northern Rocky Mountain Foothill Conifer Wooded Steppe",
    "5303": "Apacherian-Chihuahuan Semi-Desert Grassland and Steppe",
    "5304": "Chihuahuan Gypsophilous Grassland and Steppe",
    "5305": "Columbia Plateau Steppe and Grassland",
    "5306": "Columbia Plateau Low Sagebrush Steppe",
    "5307": "Inter-Mountain Basins Big Sagebrush Steppe",
    "5308": "Inter-Mountain Basins Montane Sagebrush Steppe",
    "5309": "Inter-Mountain Basins Semi-Desert Shrub Steppe",
    "5401": "California Maritime Chaparral",
    "5402": "California Mesic Chaparral",
    "5403": "California Montane Woodland and Chaparral",
    "5404": "California Xeric Serpentine Chaparral",
    "5405": "Madrean Oriental Chaparral",
    "5406": "Great Basin Semi-Desert Chaparral",
    "5407": "Mogollon Chaparral",
    "5408": "Northern and Central California Dry-Mesic Chaparral",
    "5409": "Sonora-Mojave Semi-Desert Chaparral",
    "5410": "Southern California Dry-Mesic Chaparral",
    "5411": "Coahuilan Chaparral",
    "5501": "California Central Valley Mixed Oak Savanna",
    "5502": "California Coastal Live Oak Woodland and Savanna",
    "5503": "California Lower Montane Blue Oak-Foothill Pine Woodland and Savanna",
    "5504": "Southern California Oak Woodland and Savanna",
    "5505": "Willamette Valley Upland Prairie and Savanna",
    "5506": "North-Central Interior Oak Savanna",
    "5507": "North-Central Oak Barrens",
    "5508": "Southern Piedmont Glade and Barrens",
    "5509": "Nashville Basin Limestone Glade",
    "5511": "Central Appalachian Alkaline Glade and Woodland",
    "5512": "Central Interior Highlands Calcareous Glade and Barrens",
    "5513": "West Gulf Coastal Plain Catahoula Barrens",
    "5514": "West Gulf Coastal Plain Nepheline Syenite Glade",
    "5515": "Laurentian Pine-Oak Barrens",
    "5516": "Klamath-Siskiyou Xeromorphic Serpentine Savanna and Chaparral",
    "5517": "Paleozoic Plateau Bluff and Talus",
    "5601": "Colorado Plateau Pinyon-Juniper Shrubland",
    "5602": "Atlantic Coastal Plain Xeric River Dune",
    "5603": "Inter-Mountain Basins Juniper Savanna",
    "5604": "Madrean Juniper Savanna",
    "5605": "Southern Rocky Mountain Ponderosa Pine Savanna",
    "5606": "Southern Rocky Mountain Juniper Woodland and Savanna",
    "5607": "Great Lakes Alvar",
    "5701": "Colorado Plateau Mixed Low Sagebrush Shrubland",
    "5702": "Columbia Plateau Scabland Shrubland",
    "5703": "Inter-Mountain Basins Mat Saltbush Shrubland",
    "5704": "Wyoming Basins Dwarf Sagebrush Shrubland and Steppe",
    "5705": "Great Basin Xeric Mixed Sagebrush Shrubland",
    "5706": "Inter-Mountain Basins Big Sagebrush Shrubland",
    "5707": "Southern Colorado Plateau Sand Shrubland",
    "5801": "Southern Appalachian Grass and Shrub Bald - Shrub Modifier",
    "5802": "Southern Appalachian Grass and Shrub Bald - Herbaceous Modifier",
    "5803": "Colorado Plateau Blackbrush-Mormon-tea Shrubland",
    "5804": "North Pacific Montane Shrubland",
    "5805": "Northwestern Great Plains Shrubland",
    "5806": "Rocky Mountain Lower Montane-Foothill Shrubland",
    "5807": "Northern Atlantic Coastal Plain Heathland and Grassland",
    "5808": "Northern Rocky Mountain Montane-Foothill Deciduous Shrubland",
    "5809": "Rocky Mountain Gambel Oak-Mixed Montane Shrubland",
    "5810": "Western Great Plains Mesquite Woodland and Shrubland",
    "5811": "Edwards Plateau Limestone Shrubland",
    "5812": "Northern Rocky Mountain Subalpine Deciduous Shrubland",
    "7101": "Mediterranean California Alpine Dry Tundra",
    "7102": "Rocky Mountain Alpine Fell-Field",
    "7103": "Rocky Mountain Dry Tundra",
    "7104": "North Pacific Alpine and Subalpine Dry Grassland",
    "7201": "Mediterranean California Subalpine Meadow",
    "7202": "North Pacific Montane Grassland",
    "7203": "Northern Rocky Mountain Lower Montane, Foothill and Valley Grassland",
    "7204": "Northern Rocky Mountain Subalpine-Upper Montane Grassland",
    "7205": "Rocky Mountain Subalpine-Montane Mesic Meadow",
    "7206": "Southern Rocky Mountain Montane-Subalpine Grassland",
    "7301": "Eastern Highland Rim Prairie and Barrens - Dry Modifier",
    "7302": "Central Mixedgrass Prairie",
    "7303": "Chihuahuan Sandy Plains Semi-Desert Grassland",
    "7304": "Columbia Basin Foothill and Canyon Dry Grassland",
    "7305": "Inter-Mountain Basins Semi-Desert Grassland",
    "7306": "Northwestern Great Plains Mixedgrass Prairie",
    "7307": "Columbia Basin Palouse Prairie",
    "7308": "Western Great Plains Foothill and Piedmont Grassland",
    "7309": "Western Great Plains Sand Prairie",
    "7310": "Western Great Plains Shortgrass Prairie",
    "7311": "Western Great Plains Tallgrass Prairie",
    "7312": "North-Central Interior Sand and Gravel Tallgrass Prairie",
    "7313": "Arkansas Valley Prairie and Woodland",
    "7314": "Northern Tallgrass Prairie",
    "7315": "Central Tallgrass Prairie",
    "7316": "Southern Blackland Tallgrass Prairie",
    "7317": "Southeastern Great Plains Tallgrass Prairie",
    "7318": "Florida Dry Prairie",
    "7319": "West Gulf Coastal Plain Northern Calcareous Prairie",
    "7320": "West Gulf Coastal Plain Southern Calcareous Prairie",
    "7321": "East Gulf Coastal Plain Jackson Prairie and Woodland",
    "7322": "Tamaulipan Savanna Grassland",
    "7323": "Tamaulipan Clay Grassland",
    "7324": "South Texas Sand Sheet Grassland",
    "7326": "Chihuahuan Loamy Plains Desert Grassland",
    "7401": "California Mesic Serpentine Grassland",
    "7402": "Great Lakes Wet-Mesic Lakeplain Prairie",
    "7501": "California Central Valley and Southern Coastal Grassland",
    "7502": "California Northern Coastal Grassland",
    "7503": "Atlantic Coastal Plain Southern Dune and Maritime Grassland",
    "7504": "Southwest Florida Dune and Coastal Grassland",
    "7505": "Texas-Louisiana Coastal Prairie",
    "7506": "East Gulf Coastal Plain Dune and Coastal Grassland",
    "7507": "Northern Atlantic Coastal Plain Dune and Swale",
    "7508": "Central and Upper Texas Coast Dune and Coastal Grassland",
    "7509": "South Texas Lomas",
    "7510": "South Texas Dune and Coastal Grassland",
    "7601": "Southern Appalachian Grass and Shrub Bald",
    "7602": "Llano Uplift Acidic Forest, Woodland and Glade",
    "7603": "North Pacific Hypermaritime Shrub and Herbaceous Headland",
    "7604": "North Pacific Herbaceous Bald and Bluff",
    "8101": "Recently Logged Areas",
    "8102": "Successional Shrub/Scrub (Utility Swath)",
    "8103": "Other - Herbaceous",
    "8106": "Harvested forest-tree regeneration",
    "8107": "Harvested forest-shrub regeneration",
    "8108": "Harvested forest-grass/herbaceous regeneration",
    "8201": "Deciduous Plantations",
    "8202": "Evergreen Plantations or Managed Pine (can include dense successional regrowth)",
    "8203": "Managed Tree Plantation",
    "8301": "Recently Burned",
    "8302": "Recently burned forest",
    "8303": "Recently burned grassland",
    "8304": "Recently burned shrubland",
    "8401": "Introduced Upland Vegetation - Treed",
    "8402": "Introduced Upland Vegetation - Shrub",
    "8404": "Introduced Upland Vegetation - Annual Grassland",
    "8406": "Introduced Riparian and Wetland Vegetation",
    "8407": "Introduced Upland Vegetation-Perennial Grassland and Forbland",
    "8408": "Modified/Managed Southern Tall Grassland",
    "8501": "Disturbed, Non-specific",
    "8502": "Recently Chained Pinyon-Juniper Areas",
    "8504": "Ruderal Wetland",
    "9101": "Acadian Salt Marsh and Estuary Systems",
    "9102": "North Pacific Maritime Eelgrass Bed",
    "9103": "Atlantic Coastal Plain Central Salt and Brackish Tidal Marsh",
    "9104": "Atlantic Coastal Plain Indian River Lagoon Tidal Marsh",
    "9105": "Atlantic Coastal Plain Embayed Region Tidal Salt and Brackish Marsh",
    "9106": "Mississippi Sound Salt and Brackish Tidal Marsh",
    "9107": "Mediterranean California Eelgrass Bed",
    "9108": "Temperate Pacific Tidal Salt and Brackish Marsh",
    "9109": "Atlantic Coastal Plain Northern Tidal Salt Marsh",
    "9110": "Florida Big Bend Salt-Brackish Tidal Marsh",
    "9201": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Taxodium Modifier",
    "9202": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Bay/Gum Modifier",
    "9203": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Pine Modifier",
    "9204": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Nupea Modifier",
    "9205": "Southern Coastal Plain Nonriverine Basin Swamp - Okefenokee Clethra Modifier",
    "9206": "Atlantic Coastal Plain Clay-Based Carolina Bay Herbaceous Wetland",
    "9207": "Atlantic Coastal Plain Peatland Pocosin",
    "9208": "Southern Coastal Plain Seepage Swamp and Baygall",
    "9209": "West Gulf Coastal Plain Seepage Swamp and Baygall",
    "9210": "East Gulf Coastal Plain Tidal Wooded Swamp",
    "9211": "Atlantic Coastal Plain Streamhead Seepage Swamp -  Pocosin -  and Baygall",
    "9212": "Central Interior and Appalachian Swamp Systems",
    "9213": "Gulf and Atlantic Coastal Plain Swamp Systems",
    "9214": "Laurentian-Acadian Swamp Systems",
    "9215": "Atlantic Coastal Plain Large Natural Lakeshore",
    "9216": "North Pacific Shrub Swamp",
    "9218": "Atlantic Coastal Plain Southern Tidal Wooded Swamp",
    "9219": "South Florida Everglades Sawgrass Marsh",
    "9220": "Gulf and Atlantic Coastal Plain Tidal Marsh Systems",
    "9221": "Great Lakes Coastal Marsh Systems",
    "9222": "Central Interior and Appalachian Shrub-Herbaceous Wetland Systems",
    "9223": "Floridian Highlands Freshwater Marsh",
    "9224": "Laurentian-Acadian Shrub-Herbaceous Wetland Systems",
    "9225": "Temperate Pacific Freshwater Aquatic Bed",
    "9226": "North Pacific Intertidal Freshwater Wetland",
    "9227": "North American Arid West Emergent Marsh",
    "9228": "Temperate Pacific Freshwater Emergent Marsh",
    "9229": "Great Lakes Freshwater Estuary and Delta",
    "9230": "Atlantic Coastal Plain Embayed Region Tidal Freshwater Marsh",
    "9231": "Central Florida Herbaceous Seep",
    "9232": "Florida Big Bend Fresh-Oligohaline Tidal Marsh",
    "9233": "Atlantic Coastal Plain Northern Fresh and Oligohaline Tidal Marsh",
    "9234": "Northern Great Lakes Coastal Marsh",
    "9235": "Atlantic Coastal Plain Northern Tidal Wooded Swamp",
    "9236": "South Florida Mangrove Swamp",
    "9237": "West Gulf Coastal Plain Near-Coast Large River Swamp",
    "9238": "South Florida Bayhead Swamp",
    "9239": "Southern Coastal Plain Nonriverine Basin Swamp",
    "9240": "Northern Atlantic Coastal Plain Basin Swamp and Wet Hardwood Forest",
    "9241": "Southern Coastal Plain Herbaceous Seepage Bog",
    "9242": "Laurentian-Acadian Freshwater Marsh",
    "9243": "Atlantic Coastal Plain Central Fresh-Oligohaline Tidal Marsh",
    "9301": "Atlantic Coastal Plain Nonriverine Swamp and Wet Hardwood Forest  - Taxodium/Nyssa Modifier",
    "9302": "Atlantic Coastal Plain Nonriverine Swamp and Wet Hardwood Forest - Oak Dominated Modifier",
    "9303": "Atlantic Coastal Plain Clay-Based Carolina Bay Forested Wetland",
    "9304": "Northern Rocky Mountain Conifer Swamp",
    "9305": "South Florida Dwarf Cypress Savanna",
    "9306": "North Pacific Hardwood-Conifer Swamp",
    "9307": "Northern Pacific Mesic Subalpine Woodland",
    "9308": "Laurentian-Acadian Alkaline Conifer-Hardwood Swamp",
    "9401": "Atlantic and Gulf Coastal Plain Interdunal Wetland",
    "9402": "Great Lakes Wooded Dune and Swale",
    "9403": "Inter-Mountain Basins Interdunal Swale Wetland",
    "9501": "Boreal Acidic Peatland Systems",
    "9502": "North Pacific Bog and Fen",
    "9503": "Rocky Mountain Subalpine-Montane Fen",
    "9504": "Mediterranean California Subalpine-Montane Fen",
    "9506": "Southern and Central Appalachian Bog and Fen",
    "9602": "South Florida Wet Marl Prairie",
    "9603": "East Gulf Coastal Plain Savanna and Wet Prairie",
    "9604": "Texas Saline Coastal Prairie",
    "9605": "Eastern Great Plains Wet Meadow, Prairie, and Marsh",
    "9606": "Rocky Mountain Alpine-Montane Wet Meadow",
    "9607": "Willamette Valley Wet Prairie",
    "9608": "Temperate Pacific Montane Wet Meadow",
    "9609": "Columbia Plateau Silver Sagebrush Seasonally Flooded Shrub-Steppe",
    "9610": "Chihuahuan-Sonoran Desert Bottomland and Swale Grassland",
    "9701": "Lower Mississippi River Bottomland Depressions - Forest Modifier",
    "9702": "South Florida Cypress Dome",
    "9703": "Southern Coastal Plain Nonriverine Cypress Dome",
    "9704": "Northern Rocky Mountain Wooded Vernal Pool",
    "9705": "Great Plains Prairie Pothole",
    "9706": "Western Great Plains Depressional Wetland Systems",
    "9707": "Western Great Plains Open Freshwater Depression Wetland",
    "9708": "Columbia Plateau Vernal Pool",
    "9709": "Northern California Claypan Vernal Pool",
    "9710": "Western Great Plains Closed Depression Wetland",
    "9711": "Western Great Plains Saline Depression Wetland",
    "9712": "Central Florida Herbaceous Pondshore",
    "9713": "East Gulf Coastal Plain Southern Depression Pondshore",
    "9714": "Inter-Mountain Basins Alkaline Closed Depression",
    "9715": "Southern Piedmont/Ridge and Valley Upland Depression Swamp",
    "9716": "Atlantic Coastal Plain Depression Pondshore",
    "9717": "Mississippi River Bottomland Depression",
    "9718": "South Florida Freshwater Slough and Gator Hole",
    "9801": "Atlantic Coastal Plain Blackwater Stream Floodplain Forest - Forest Modifier",
    "9802": "Central Appalachian Floodplain - Forest Modifier",
    "9803": "Central Appalachian Riparian - Forest Modifier",
    "9804": "East Gulf Coastal Plain Large River Floodplain Forest - Forest Modifier",
    "9805": "South-Central Interior Large Floodplain - Forest Modifier",
    "9806": "Southern Piedmont Large Floodplain Forest - Forest Modifier",
    "9807": "East Gulf Coastal Plain Large River Floodplain Forest - Herbaceous Modifier",
    "9808": "South-Central Interior Large Floodplain - Herbaceous Modifier",
    "9809": "California Central Valley Riparian Woodland and Shrubland",
    "9810": "Inter-Mountain Basins Greasewood Flat",
    "9811": "North Pacific Lowland Riparian Forest and Shrubland",
    "9812": "North Pacific Montane Riparian Woodland and Shrubland",
    "9813": "Rocky Mountain Montane Riparian Systems",
    "9814": "Western Great Plains Floodplain Systems",
    "9815": "Eastern Boreal Floodplain",
    "9816": "Tamaulipan Floodplain",
    "9817": "Eastern Great Plains Floodplain Systems",
    "9818": "Central Interior and Appalachian Floodplain Systems",
    "9819": "Central Interior and Appalachian Riparian Systems",
    "9820": "Laurentian-Acadian Floodplain Systems",
    "9821": "Tamaulipan Riparian Systems",
    "9822": "North American Warm Desert Wash",
    "9823": "Western Great Plains Floodplain",
    "9824": "Northern Rocky Mountain Lower Montane Riparian Woodland and Shrubland",
    "9825": "Rocky Mountain Lower Montane Riparian Woodland and Shrubland",
    "9826": "Northwestern Great Plains Floodplain",
    "9827": "Mississippi River Riparian Forest",
    "9828": "Cumberland Riverscour",
    "9829": "Edwards Plateau Riparian",
    "9830": "Great Basin Foothill and Lower Montane Riparian Woodland and Shrubland",
    "9831": "Columbia Basin Foothill Riparian Woodland and Shrubland",
    "9832": "Rocky Mountain Subalpine-Montane Riparian Woodland",
    "9833": "North American Warm Desert Lower Montane Riparian Woodland and Shrubland",
    "9834": "North American Warm Desert Riparian Mesquite Bosque",
    "9835": "North American Warm Desert Riparian Woodland and Shrubland",
    "9836": "Mississippi River Low Floodplain (Bottomland) Forest",
    "9837": "Rocky Mountain Subalpine-Montane Riparian Shrubland",
    "9838": "Southern Coastal Plain Hydric Hammock",
    "9839": "West Gulf Coastal Plain Small Stream and River Forest",
    "9840": "West Gulf Coastal Plain Large River Floodplain Forest",
    "9841": "Southern Piedmont Small Floodplain and Riparian Forest",
    "9842": "Atlantic Coastal Plain Small Brownwater River Floodplain Forest",
    "9843": "Atlantic Coastal Plain Small Blackwater River Floodplain Forest",
    "9844": "Red River Large Floodplain Forest",
    "9845": "Atlantic Coastal Plain Brownwater Stream Floodplain Forest",
    "9846": "Mediterranean California Serpentine Foothill and Lower Montane Riparian Woodland and Seep",
    "9847": "Northwestern Great Plains Riparian",
    "9848": "Western Great Plains Riparian Woodland and Shrubland",
    "9849": "Mediterranean California Foothill and Lower Montane Riparian Woodland",
    "9850": "South-Central Interior Small Stream and Riparian",
    "9851": "East Gulf Coastal Plain Small Stream and River Floodplain Forest",
    "9852": "Southern Coastal Plain Blackwater River Floodplain Forest",
    "9853": "Texas-Louisiana Coastal Prairie Slough",
    "9854": "Mississippi River Floodplain and Riparian Forest",
    "9855": "Inter-Mountain Basins Montane Riparian Systems",
    "9856": "North American Warm Desert Riparian Systems",
    "9857": "South-Central Interior Large Floodplain",
    "9858": "Ozark-Ouachita Riparian",
    "9901": "East Gulf Coastal Plain Jackson Plain Dry Flatwoods - Open Understory Modifier",
    "9902": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Offsite Hardwood Modifier",
    "9903": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Open Understory Modifier",
    "9904": "East Gulf Coastal Plain Near-Coast Pine Flatwoods - Scrub/Shrub Understory Modifier",
    "9905": "South Florida Pine Flatwoods",
    "9906": "Central Atlantic Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "9907": "Atlantic Coastal Plain Southern Wet Pine Savanna and Flatwoods",
    "9908": "West Gulf Coastal Plain Wet Longleaf Pine Savanna and Flatwoods",
    "9909": "Central Florida Pine Flatwoods",
    "9911": "East Gulf Coastal Plain Southern Loblolly-Hardwood Flatwoods",
    "9912": "South-Central Interior / Upper Coastal Plain Wet Flatwoods",
    "9913": "West Gulf Coastal Plain Pine-Hardwood Flatwoods",
    "9914": "North-Central Interior Wet Flatwoods",
    "9915": "Lower Mississippi River Flatwoods",
    "9916": "West Gulf Coastal Plain Nonriverine Wet Hardwood Flatwoods"
  },
  "LANDFIREFuelModel40": {
    "91": "NB1",
    "93": "NB3",
    "98": "NB8",
    "99": "NB9",
    "101": "GR1",
    "102": "GR2",
    "103": "GR3",
    "105": "GR5",
    "108": "GR8",
    "121": "GS1",
    "122": "GS2",
    "123": "GS3",
    "124": "GS4",
    "141": "SH1",
    "142": "SH2",
    "143": "SH3",
    "144": "SH4",
    "146": "SH6",
    "147": "SH7",
    "148": "SH8",
    "149": "SH9",
    "161": "TU1",
    "162": "TU2",
    "163": "TU3",
    "165": "TU5",
    "181": "TL1",
    "182": "TL2",
    "183": "TL3",
    "184": "TL4",
    "185": "TL5",
    "186": "TL6",
    "188": "TL8",
    "189": "TL9",
    "201": "SB1",
    "202": "SB2",
    "203": "SB3"
  },
  "landcover-2005-NALCMS": {
    "1": "Temperate or sub-polar needleleaf forest",
    "2": "Sub-polar taiga needleleaf forest",
    "3": "Tropical or sub-tropical broadleaf evergreen forest",
    "4": "Tropical or sub-tropical broadleaf deciduous forest",
    "5": "Temperate or sub-polar broadleaf deciduous forest",
    "6": "Mixed forest",
    "7": "Tropical or sub-tropical shrubland",
    "8": "Temperate or sub-polar shrubland",
    "9": "Tropical or sub-tropical grassland",
    "10": "Temperate or sub-polar grassland",
    "11": "Sub-polar or polar shrubland-lichen-moss",
    "12": "Sub-polar or polar grassland-lichen-moss",
    "13": "Sub-polar or polar barren-lichen-moss",
    "14": "Wetland",
    "15": "Cropland",
    "16": "Barren land",
    "17": "Urban and built-up",
    "18": "Water",
    "19": "Snow and ice"
  },
  "landcover-2010-NALCMS": {
    "1": "Temperate or sub-polar needleleaf forest",
    "2": "Sub-polar taiga needleleaf forest",
    "3": "Tropical or sub-tropical broadleaf evergreen forest",
    "4": "Tropical or sub-tropical broadleaf deciduous forest",
    "5": "Temperate or sub-polar broadleaf deciduous forest",
    "6": "Mixed forest",
    "7": "Tropical or sub-tropical shrubland",
    "8": "Temperate or sub-polar shrubland",
    "9": "Tropical or sub-tropical grassland",
    "10": "Temperate or sub-polar grassland",
    "11": "Sub-polar or polar shrubland-lichen-moss",
    "12": "Sub-polar or polar grassland-lichen-moss",
    "13": "Sub-polar or polar barren-lichen-moss",
    "14": "Wetland",
    "15": "Cropland",
    "16": "Barren land",
    "17": "Urban and built-up",
    "18": "Water",
    "19": "Snow and ice"
  },
  "CropLands2013": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  },
  "CropLands2015": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "51": "Chick Peas",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "63": "Forest",
    "64": "Shrubland",
    "65": "Barren",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "81": "Clouds/No Data",
    "82": "Developed",
    "83": "Water",
    "87": "Wetlands",
    "88": "Nonag/Undefined",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "210": "Prunes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  },
  "CropLands2014": {
    "0": "Background",
    "1": "Corn",
    "2": "Cotton",
    "3": "Rice",
    "4": "Sorghum",
    "5": "Soybeans",
    "6": "Sunflower",
    "10": "Peanuts",
    "11": "Tobacco",
    "12": "Sweet Corn",
    "13": "Pop or Orn Corn",
    "14": "Mint",
    "21": "Barley",
    "22": "Durum Wheat",
    "23": "Spring Wheat",
    "24": "Winter Wheat",
    "25": "Other Small Grains",
    "26": "Dbl Crop WinWht/Soybeans",
    "27": "Rye",
    "28": "Oats",
    "29": "Millet",
    "30": "Speltz",
    "31": "Canola",
    "32": "Flaxseed",
    "33": "Safflower",
    "34": "Rape Seed",
    "35": "Mustard",
    "36": "Alfalfa",
    "37": "Other Hay/Non Alfalfa",
    "38": "Camelina",
    "39": "Buckwheat",
    "41": "Sugarbeets",
    "42": "Dry Beans",
    "43": "Potatoes",
    "44": "Other Crops",
    "45": "Sugarcane",
    "46": "Sweet Potatoes",
    "47": "Misc Vegs & Fruits",
    "48": "Watermelons",
    "49": "Onions",
    "50": "Cucumbers",
    "51": "Chick Peas",
    "52": "Lentils",
    "53": "Peas",
    "54": "Tomatoes",
    "55": "Caneberries",
    "56": "Hops",
    "57": "Herbs",
    "58": "Clover/Wildflowers",
    "59": "Sod/Grass Seed",
    "60": "Switchgrass",
    "61": "Fallow/Idle Cropland",
    "63": "Forest",
    "64": "Shrubland",
    "65": "Barren",
    "66": "Cherries",
    "67": "Peaches",
    "68": "Apples",
    "69": "Grapes",
    "70": "Christmas Trees",
    "71": "Other Tree Crops",
    "72": "Citrus",
    "74": "Pecans",
    "75": "Almonds",
    "76": "Walnuts",
    "77": "Pears",
    "81": "Clouds/No Data",
    "82": "Developed",
    "83": "Water",
    "87": "Wetlands",
    "88": "Nonag/Undefined",
    "92": "Aquaculture",
    "111": "Open Water",
    "112": "Perennial Ice/Snow",
    "121": "Developed/Open Space",
    "122": "Developed/Low Intensity",
    "123": "Developed/Med Intensity",
    "124": "Developed/High Intensity",
    "131": "Barren",
    "141": "Deciduous Forest",
    "142": "Evergreen Forest",
    "143": "Mixed Forest",
    "152": "Shrubland",
    "176": "Grassland/Pasture",
    "190": "Woody Wetlands",
    "195": "Herbaceous Wetlands",
    "204": "Pistachios",
    "205": "Triticale",
    "206": "Carrots",
    "207": "Asparagus",
    "208": "Garlic",
    "209": "Cantaloupes",
    "210": "Prunes",
    "211": "Olives",
    "212": "Oranges",
    "213": "Honeydew Melons",
    "214": "Broccoli",
    "216": "Peppers",
    "217": "Pomegranates",
    "218": "Nectarines",
    "219": "Greens",
    "220": "Plums",
    "221": "Strawberries",
    "222": "Squash",
    "223": "Apricots",
    "224": "Vetch",
    "225": "Dbl Crop WinWht/Corn",
    "226": "Dbl Crop Oats/Corn",
    "227": "Lettuce",
    "229": "Pumpkins",
    "230": "Dbl Crop Lettuce/Durum Wht",
    "231": "Dbl Crop Lettuce/Cantaloupe",
    "232": "Dbl Crop Lettuce/Cotton",
    "233": "Dbl Crop Lettuce/Barley",
    "234": "Dbl Crop Durum Wht/Sorghum",
    "235": "Dbl Crop Barley/Sorghum",
    "236": "Dbl Crop WinWht/Sorghum",
    "237": "Dbl Crop Barley/Corn",
    "238": "Dbl Crop WinWht/Cotton",
    "239": "Dbl Crop Soybeans/Cotton",
    "240": "Dbl Crop Soybeans/Oats",
    "241": "Dbl Crop Corn/Soybeans",
    "242": "Blueberries",
    "243": "Cabbage",
    "244": "Cauliflower",
    "245": "Celery",
    "246": "Radishes",
    "247": "Turnips",
    "248": "Eggplants",
    "249": "Gourds",
    "250": "Cranberries",
    "254": "Dbl Crop Barley/Soybeans"
  }
}
